/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CloseConversation200Handler = typeof CloseConversation200Handler[keyof typeof CloseConversation200Handler];


export const CloseConversation200Handler = {
  AI: 'AI',
  QUEUE: 'QUEUE',
  HUMAN: 'HUMAN',
} as const;
