/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CloseConversation200ChannelKind = typeof CloseConversation200ChannelKind[keyof typeof CloseConversation200ChannelKind];


export const CloseConversation200ChannelKind = {
  WEB_CHAT: 'WEB_CHAT',
} as const;
