/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { CloseConversation200Channel } from './closeConversation200Channel';
import type { CloseConversation200Contact } from './closeConversation200Contact';
import type { CloseConversation200Handler } from './closeConversation200Handler';
import type { CloseConversation200Status } from './closeConversation200Status';

export type CloseConversation200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  status: CloseConversation200Status;
  handler: CloseConversation200Handler;
  assigneeId: string | null;
  contact: CloseConversation200Contact;
  channel: CloseConversation200Channel;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  lastSeq: number;
  lastMessageAt: string | null;
  closedAt: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  createdAt: string;
};
