/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CloseConversation200Status = typeof CloseConversation200Status[keyof typeof CloseConversation200Status];


export const CloseConversation200Status = {
  OPEN: 'OPEN',
  WAITING: 'WAITING',
  CLOSED: 'CLOSED',
} as const;
