/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateInvitation200Role = typeof CreateInvitation200Role[keyof typeof CreateInvitation200Role];


export const CreateInvitation200Role = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
} as const;
