/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type CreateInvitation200Status = typeof CreateInvitation200Status[keyof typeof CreateInvitation200Status];


export const CreateInvitation200Status = {
  PENDING: 'PENDING',
} as const;
