/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetConversation200Handler = typeof GetConversation200Handler[keyof typeof GetConversation200Handler];


export const GetConversation200Handler = {
  AI: 'AI',
  QUEUE: 'QUEUE',
  HUMAN: 'HUMAN',
} as const;
