/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetConversation200ChannelKind = typeof GetConversation200ChannelKind[keyof typeof GetConversation200ChannelKind];


export const GetConversation200ChannelKind = {
  WEB_CHAT: 'WEB_CHAT',
} as const;
