/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetConversation200Status = typeof GetConversation200Status[keyof typeof GetConversation200Status];


export const GetConversation200Status = {
  OPEN: 'OPEN',
  WAITING: 'WAITING',
  CLOSED: 'CLOSED',
} as const;
