/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetMe200PermissionsItem = typeof GetMe200PermissionsItem[keyof typeof GetMe200PermissionsItem];


export const GetMe200PermissionsItem = {
  'organization:read': 'organization:read',
  'organization:update': 'organization:update',
} as const;
