/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetMe200OrganizationsItem } from './getMe200OrganizationsItem';
import type { GetMe200PermissionsItem } from './getMe200PermissionsItem';
import type { GetMe200Role } from './getMe200Role';
import type { GetMe200Terms } from './getMe200Terms';

export type GetMe200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @pattern ^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  emailVerified: boolean;
  twoFactorEnabled: boolean;
  isSuperAdmin: boolean;
  activeOrganizationId: string | null;
  role: GetMe200Role;
  permissions: GetMe200PermissionsItem[];
  organizations: GetMe200OrganizationsItem[];
  terms: GetMe200Terms;
};
