/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetMe200OrganizationsItemRole = typeof GetMe200OrganizationsItemRole[keyof typeof GetMe200OrganizationsItemRole];


export const GetMe200OrganizationsItemRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
  VIEWER: 'VIEWER',
} as const;
