/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetOrganization200Role = typeof GetOrganization200Role[keyof typeof GetOrganization200Role];


export const GetOrganization200Role = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
} as const;
