/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetPublicInvitation200Role = typeof GetPublicInvitation200Role[keyof typeof GetPublicInvitation200Role];


export const GetPublicInvitation200Role = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
} as const;
