/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetPublicChat200 = {
  name: string;
  /** @nullable */
  brandColor: string | null;
  /** @nullable */
  greeting: string | null;
  hasLogo: boolean;
  noticeVersion: string;
  /** @nullable */
  turnstileSiteKey: string | null;
};
