/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetPublicInvitation200Status = typeof GetPublicInvitation200Status[keyof typeof GetPublicInvitation200Status];


export const GetPublicInvitation200Status = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
} as const;
