/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { GetSignupConfig200SignupMode } from './getSignupConfig200SignupMode';

export type GetSignupConfig200 = {
  signupMode: GetSignupConfig200SignupMode;
  /** @nullable */
  turnstileSiteKey: string | null;
};
