/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type GetSignupConfig200SignupMode = typeof GetSignupConfig200SignupMode[keyof typeof GetSignupConfig200SignupMode];


export const GetSignupConfig200SignupMode = {
  closed: 'closed',
  self_serve: 'self_serve',
} as const;
