/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListConversationMessages200ItemsItem } from './listConversationMessages200ItemsItem';

export type ListConversationMessages200 = {
  items: ListConversationMessages200ItemsItem[];
  nextCursor: string | null;
};
