/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListConversations200ItemsItem } from './listConversations200ItemsItem';

export type ListConversations200 = {
  items: ListConversations200ItemsItem[];
  nextCursor: string | null;
};
