/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversationMessages200ItemsItemKind = typeof ListConversationMessages200ItemsItemKind[keyof typeof ListConversationMessages200ItemsItemKind];


export const ListConversationMessages200ItemsItemKind = {
  TEXT: 'TEXT',
  UNSUPPORTED: 'UNSUPPORTED',
} as const;
