/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversations200ItemsItemChannelKind = typeof ListConversations200ItemsItemChannelKind[keyof typeof ListConversations200ItemsItemChannelKind];


export const ListConversations200ItemsItemChannelKind = {
  WEB_CHAT: 'WEB_CHAT',
} as const;
