/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPublicChatMessages200ItemsItemDirection = typeof ListPublicChatMessages200ItemsItemDirection[keyof typeof ListPublicChatMessages200ItemsItemDirection];


export const ListPublicChatMessages200ItemsItemDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;
