/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversationMessages200ItemsItemDeliveryStatus = typeof ListConversationMessages200ItemsItemDeliveryStatus[keyof typeof ListConversationMessages200ItemsItemDeliveryStatus] | null;


export const ListConversationMessages200ItemsItemDeliveryStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
} as const;
