/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversations200ItemsItemStatus = typeof ListConversations200ItemsItemStatus[keyof typeof ListConversations200ItemsItemStatus];


export const ListConversations200ItemsItemStatus = {
  OPEN: 'OPEN',
  WAITING: 'WAITING',
  CLOSED: 'CLOSED',
} as const;
