/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversationMessages200ItemsItemAuthor = typeof ListConversationMessages200ItemsItemAuthor[keyof typeof ListConversationMessages200ItemsItemAuthor];


export const ListConversationMessages200ItemsItemAuthor = {
  CONTACT: 'CONTACT',
  AI: 'AI',
  HUMAN: 'HUMAN',
  SYSTEM: 'SYSTEM',
} as const;
