/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversationMessages200ItemsItemDirection = typeof ListConversationMessages200ItemsItemDirection[keyof typeof ListConversationMessages200ItemsItemDirection];


export const ListConversationMessages200ItemsItemDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;
