/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversationsView = typeof ListConversationsView[keyof typeof ListConversationsView];


export const ListConversationsView = {
  queue: 'queue',
  mine: 'mine',
} as const;
