/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListConversations200ItemsItemHandler = typeof ListConversations200ItemsItemHandler[keyof typeof ListConversations200ItemsItemHandler];


export const ListConversations200ItemsItemHandler = {
  AI: 'AI',
  QUEUE: 'QUEUE',
  HUMAN: 'HUMAN',
} as const;
