/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListMembers200ItemsItemRole = typeof ListMembers200ItemsItemRole[keyof typeof ListMembers200ItemsItemRole];


export const ListMembers200ItemsItemRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
} as const;
