/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPublicChatMessages200ItemsItemKind = typeof ListPublicChatMessages200ItemsItemKind[keyof typeof ListPublicChatMessages200ItemsItemKind];


export const ListPublicChatMessages200ItemsItemKind = {
  TEXT: 'TEXT',
  UNSUPPORTED: 'UNSUPPORTED',
} as const;
