/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListMembers200ItemsItem } from './listMembers200ItemsItem';

export type ListMembers200 = {
  items: ListMembers200ItemsItem[];
};
