/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListInvitations200ItemsItemRole = typeof ListInvitations200ItemsItemRole[keyof typeof ListInvitations200ItemsItemRole];


export const ListInvitations200ItemsItemRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
  VIEWER: 'VIEWER',
} as const;
