/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListPublicChatMessages200ItemsItem } from './listPublicChatMessages200ItemsItem';

export type ListPublicChatMessages200 = {
  items: ListPublicChatMessages200ItemsItem[];
};
