/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPublicChatMessages200ItemsItemAuthor = typeof ListPublicChatMessages200ItemsItemAuthor[keyof typeof ListPublicChatMessages200ItemsItemAuthor];


export const ListPublicChatMessages200ItemsItemAuthor = {
  CONTACT: 'CONTACT',
  AI: 'AI',
  HUMAN: 'HUMAN',
  SYSTEM: 'SYSTEM',
} as const;
