/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type ListPublicChatMessagesParams = {
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
after?: number;
};
