/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { ListInvitations200ItemsItem } from './listInvitations200ItemsItem';

export type ListInvitations200 = {
  items: ListInvitations200ItemsItem[];
};
