/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type OnboardOrganization200Role = typeof OnboardOrganization200Role[keyof typeof OnboardOrganization200Role];


export const OnboardOrganization200Role = {
  OWNER: 'OWNER',
} as const;
