/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type PreviewExampleCommission200 = {
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  brokerageAmountCents: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  salespersonAmountCents: number;
};
