/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type PreviewExampleCommissionParams = {
/**
 * @minimum 0
 * @maximum 9007199254740991
 */
premiumCents: number;
/**
 * @minimum 0
 * @maximum 10000
 */
rateBp: number;
/**
 * @minimum 0
 * @maximum 10000
 */
splitBp: number;
};
