/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type RenameOrganizationBody = {
  /**
     * @minLength 2
     * @maxLength 80
     */
  name: string;
};
