/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type RevokeInvitation200Status = typeof RevokeInvitation200Status[keyof typeof RevokeInvitation200Status];


export const RevokeInvitation200Status = {
  REVOKED: 'REVOKED',
} as const;
