/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendConversationMessageBody = {
  /**
     * @minLength 1
     * @maxLength 4000
     */
  text: string;
};
