/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendConversationMessage201MessageAuthor = typeof SendConversationMessage201MessageAuthor[keyof typeof SendConversationMessage201MessageAuthor];


export const SendConversationMessage201MessageAuthor = {
  CONTACT: 'CONTACT',
  AI: 'AI',
  HUMAN: 'HUMAN',
  SYSTEM: 'SYSTEM',
} as const;
