/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SendConversationMessage201Message } from './sendConversationMessage201Message';

export type SendConversationMessage201 = {
  message: SendConversationMessage201Message;
};
