/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendPublicChatMessage200MessageKind = typeof SendPublicChatMessage200MessageKind[keyof typeof SendPublicChatMessage200MessageKind];


export const SendPublicChatMessage200MessageKind = {
  TEXT: 'TEXT',
  UNSUPPORTED: 'UNSUPPORTED',
} as const;
