/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SendPublicChatMessage201Message } from './sendPublicChatMessage201Message';

export type SendPublicChatMessage201 = {
  message: SendPublicChatMessage201Message;
};
