/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendPublicChatMessage200MessageAuthor = typeof SendPublicChatMessage200MessageAuthor[keyof typeof SendPublicChatMessage200MessageAuthor];


export const SendPublicChatMessage200MessageAuthor = {
  CONTACT: 'CONTACT',
  AI: 'AI',
  HUMAN: 'HUMAN',
  SYSTEM: 'SYSTEM',
} as const;
