/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendConversationMessage201MessageKind = typeof SendConversationMessage201MessageKind[keyof typeof SendConversationMessage201MessageKind];


export const SendConversationMessage201MessageKind = {
  TEXT: 'TEXT',
  UNSUPPORTED: 'UNSUPPORTED',
} as const;
