/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SendPublicChatMessage200Message } from './sendPublicChatMessage200Message';

export type SendPublicChatMessage200 = {
  message: SendPublicChatMessage200Message;
};
