/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendPublicChatMessage201MessageAuthor = typeof SendPublicChatMessage201MessageAuthor[keyof typeof SendPublicChatMessage201MessageAuthor];


export const SendPublicChatMessage201MessageAuthor = {
  CONTACT: 'CONTACT',
  AI: 'AI',
  HUMAN: 'HUMAN',
  SYSTEM: 'SYSTEM',
} as const;
