/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendConversationMessage201MessageDeliveryStatus = typeof SendConversationMessage201MessageDeliveryStatus[keyof typeof SendConversationMessage201MessageDeliveryStatus] | null;


export const SendConversationMessage201MessageDeliveryStatus = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
} as const;
