/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendConversationMessage201MessageDirection = typeof SendConversationMessage201MessageDirection[keyof typeof SendConversationMessage201MessageDirection];


export const SendConversationMessage201MessageDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;
