/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendPublicChatMessage201MessageDirection = typeof SendPublicChatMessage201MessageDirection[keyof typeof SendPublicChatMessage201MessageDirection];


export const SendPublicChatMessage201MessageDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;
