/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendPublicChatMessage201MessageKind = typeof SendPublicChatMessage201MessageKind[keyof typeof SendPublicChatMessage201MessageKind];


export const SendPublicChatMessage201MessageKind = {
  TEXT: 'TEXT',
  UNSUPPORTED: 'UNSUPPORTED',
} as const;
