/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { SendPublicChatMessage201MessageAuthor } from './sendPublicChatMessage201MessageAuthor';
import type { SendPublicChatMessage201MessageDirection } from './sendPublicChatMessage201MessageDirection';
import type { SendPublicChatMessage201MessageKind } from './sendPublicChatMessage201MessageKind';

export type SendPublicChatMessage201Message = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  seq: number;
  direction: SendPublicChatMessage201MessageDirection;
  author: SendPublicChatMessage201MessageAuthor;
  kind: SendPublicChatMessage201MessageKind;
  /** @nullable */
  text: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  sentAt: string;
};
