/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SendPublicChatMessage200MessageDirection = typeof SendPublicChatMessage200MessageDirection[keyof typeof SendPublicChatMessage200MessageDirection];


export const SendPublicChatMessage200MessageDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;
