/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type SetActiveOrganization200Role = typeof SetActiveOrganization200Role[keyof typeof SetActiveOrganization200Role];


export const SetActiveOrganization200Role = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  COMMERCIAL: 'COMMERCIAL',
  VIEWER: 'VIEWER',
} as const;
