/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type StartPublicChatSessionBody = {
  /**
     * @minLength 1
     * @maxLength 40
     */
  phone: string;
  consent: true;
  /**
     * @minLength 1
     * @maxLength 40
     */
  noticeVersion: string;
  /** @maxLength 4096 */
  turnstileToken: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  clientMessageId: string;
  /**
     * @minLength 1
     * @maxLength 4000
     */
  text: string;
};
