/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type StartPublicChatSession201MessageDirection = typeof StartPublicChatSession201MessageDirection[keyof typeof StartPublicChatSession201MessageDirection];


export const StartPublicChatSession201MessageDirection = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
} as const;
