/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type StartPublicChatSession201MessageAuthor = typeof StartPublicChatSession201MessageAuthor[keyof typeof StartPublicChatSession201MessageAuthor];


export const StartPublicChatSession201MessageAuthor = {
  CONTACT: 'CONTACT',
  AI: 'AI',
  HUMAN: 'HUMAN',
  SYSTEM: 'SYSTEM',
} as const;
