/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { StartPublicChatSession201Message } from './startPublicChatSession201Message';

export type StartPublicChatSession201 = {
  message: StartPublicChatSession201Message;
  /** @minLength 1 */
  token: string;
};
