/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type StartPublicChatSession201MessageKind = typeof StartPublicChatSession201MessageKind[keyof typeof StartPublicChatSession201MessageKind];


export const StartPublicChatSession201MessageKind = {
  TEXT: 'TEXT',
  UNSUPPORTED: 'UNSUPPORTED',
} as const;
