/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type TakeConversation200Status = typeof TakeConversation200Status[keyof typeof TakeConversation200Status];


export const TakeConversation200Status = {
  OPEN: 'OPEN',
  WAITING: 'WAITING',
  CLOSED: 'CLOSED',
} as const;
