/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type TakeConversation200Handler = typeof TakeConversation200Handler[keyof typeof TakeConversation200Handler];


export const TakeConversation200Handler = {
  AI: 'AI',
  QUEUE: 'QUEUE',
  HUMAN: 'HUMAN',
} as const;
