/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */

export type TakeConversation200ChannelKind = typeof TakeConversation200ChannelKind[keyof typeof TakeConversation200ChannelKind];


export const TakeConversation200ChannelKind = {
  WEB_CHAT: 'WEB_CHAT',
} as const;
