/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateMemberBodyRole } from './updateMemberBodyRole';

export type UpdateMemberBody = {
  role?: UpdateMemberBodyRole;
  active?: boolean;
};
