import { randomBytes, randomUUID } from 'node:crypto'
import { readFileSync } from 'node:fs'
import type pg from 'pg'
import { beforeAll, describe, expect, it } from 'vitest'
import { prepareTestDatabase, withOwnerClient, withSchemaBefore, workerSchema } from './setup-db.ts'

// ADR-004: every table with `organizationId` has row level security enabled and forced with the
// `tenant_isolation` policy, and its unique indexes include the tenant (integrity checks bypass RLS).
// Checked in the PostgreSQL catalog of this worker's schema, which the real migrations built.

async function findUnprotectedTenantTables(client: pg.Client, schema: string) {
  const { rows } = await client.query<{ table: string }>(
    `SELECT c.relname AS table
       FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relkind = 'r'
        AND EXISTS (SELECT 1 FROM pg_attribute a
                     WHERE a.attrelid = c.oid AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND NOT (c.relrowsecurity AND c.relforcerowsecurity AND EXISTS (
              SELECT 1 FROM pg_policies p
               WHERE p.schemaname = n.nspname AND p.tablename = c.relname
                 AND p.policyname = 'tenant_isolation'))
      ORDER BY 1`,
    [schema],
  )
  return rows.map((row) => row.table)
}

// Primary keys are excluded: ids are generated by the server (UUID v7), never taken from input.
async function findUniqueIndexesWithoutTenant(client: pg.Client, schema: string) {
  const { rows } = await client.query<{ index: string }>(
    `SELECT i.relname AS index
       FROM pg_index x
       JOIN pg_class t ON t.oid = x.indrelid
       JOIN pg_class i ON i.oid = x.indexrelid
       JOIN pg_namespace n ON n.oid = t.relnamespace
      WHERE n.nspname = $1 AND x.indisunique AND NOT x.indisprimary
        AND EXISTS (SELECT 1 FROM pg_attribute a
                     WHERE a.attrelid = t.oid AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND NOT EXISTS (SELECT 1 FROM pg_attribute a
                         WHERE a.attrelid = t.oid AND a.attname = 'organizationId'
                           AND a.attnum = ANY (x.indkey))
      ORDER BY 1`,
    [schema],
  )
  return rows.map((row) => row.index)
}

// A cascade runs as the table owner, so it ignores row security (ADR-004): from a tenant table to a
// table without organizationId, deletes and updates must not propagate.
async function findCascadingForeignKeysToUnguarded(client: pg.Client, schema: string) {
  const { rows } = await client.query<{ fk: string }>(
    `SELECT con.conname AS fk
       FROM pg_constraint con
       JOIN pg_class child ON child.oid = con.conrelid
       JOIN pg_class parent ON parent.oid = con.confrelid
       JOIN pg_namespace n ON n.oid = child.relnamespace
      WHERE n.nspname = $1 AND con.contype = 'f'
        AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = child.oid
                     AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND NOT EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = parent.oid
                         AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND (con.confdeltype NOT IN ('r', 'a') OR con.confupdtype NOT IN ('r', 'a'))
      ORDER BY 1`,
    [schema],
  )
  return rows.map((row) => row.fk)
}

// A throwaway schema next to the worker's, dropped afterwards.
function withProbeSchema<T>(label: string, run: (client: pg.Client, probe: string) => Promise<T>) {
  const probe = `${workerSchema()}_${label}_probe`
  return withOwnerClient(async (client) => {
    await client.query(`DROP SCHEMA IF EXISTS "${probe}" CASCADE`)
    await client.query(`CREATE SCHEMA "${probe}"`)
    try {
      return await run(client, probe)
    } finally {
      await client.query(`DROP SCHEMA "${probe}" CASCADE`)
    }
  })
}

beforeAll(() => prepareTestDatabase())

describe('tenant tables', () => {
  it('has no Example table', async () => {
    const { rows } = await withOwnerClient((client) =>
      client.query<{ name: string }>(
        `SELECT c.relname AS name
           FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname = $1 AND c.relname = 'Example'`,
        [workerSchema()],
      ),
    )

    expect(rows).toEqual([])
  })

  it('protects Organization with tenant_isolation', async () => {
    const { rows } = await withOwnerClient((client) =>
      client.query<{ protected: boolean }>(
        `SELECT c.relrowsecurity AND c.relforcerowsecurity AND EXISTS (
            SELECT 1 FROM pg_policies p
             WHERE p.schemaname = n.nspname AND p.tablename = c.relname
               AND p.policyname = 'tenant_isolation') AS protected
           FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname = $1 AND c.relname = 'Organization'`,
        [workerSchema()],
      ),
    )

    expect(rows).toEqual([{ protected: true }])
  })

  it('isolates invitations by tenant or token hash', async () => {
    const schema = workerSchema()
    const policy = await withOwnerClient((client) =>
      client.query<{ qual: string | null; with_check: string | null }>(
        `SELECT qual, with_check
           FROM pg_policies
          WHERE schemaname = $1 AND tablename = 'Invitation' AND policyname = 'tenant_isolation'`,
        [schema],
      ),
    )
    const indexes = await withOwnerClient((client) =>
      client.query<{ indexdef: string }>(
        `SELECT indexdef FROM pg_indexes WHERE schemaname = $1 AND tablename = 'Invitation'`,
        [schema],
      ),
    )

    expect(policy.rows).toHaveLength(1)
    expect(policy.rows[0]?.qual).toContain('app.invitation_token')
    expect(policy.rows[0]?.with_check).not.toContain('app.invitation_token')
    expect(
      indexes.rows.some(
        (row) =>
          row.indexdef.includes('UNIQUE') &&
          row.indexdef.includes('email') &&
          row.indexdef.includes('status') &&
          row.indexdef.includes('PENDING'),
      ),
    ).toBe(true)
    expect(
      indexes.rows.some(
        (row) =>
          row.indexdef.includes('UNIQUE') &&
          row.indexdef.includes('"organizationId"') &&
          row.indexdef.includes('"tokenHash"'),
      ),
    ).toBe(true)
  })

  it('isolates audit logs by tenant', async () => {
    const schema = workerSchema()
    const protectedTable = await withOwnerClient((client) =>
      client.query<{ protected: boolean }>(
        `SELECT c.relrowsecurity AND c.relforcerowsecurity AND EXISTS (
            SELECT 1 FROM pg_policies p
             WHERE p.schemaname = n.nspname AND p.tablename = c.relname
               AND p.policyname = 'tenant_isolation') AS protected
           FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname = $1 AND c.relname = 'AuditLog'`,
        [schema],
      ),
    )
    const policy = await withOwnerClient((client) =>
      client.query<{ qual: string | null; with_check: string | null }>(
        `SELECT qual, with_check
           FROM pg_policies
          WHERE schemaname = $1 AND tablename = 'AuditLog' AND policyname = 'tenant_isolation'`,
        [schema],
      ),
    )
    const indexes = await withOwnerClient((client) =>
      client.query<{ indexdef: string }>(
        `SELECT indexdef FROM pg_indexes WHERE schemaname = $1 AND tablename = 'AuditLog'`,
        [schema],
      ),
    )

    expect(protectedTable.rows).toEqual([{ protected: true }])
    expect(policy.rows[0]?.qual).toContain('app.tenant_id')
    expect(policy.rows[0]?.qual).not.toContain('app.invitation_token')
    expect(policy.rows[0]?.with_check).toContain('app.tenant_id')
    expect(policy.rows[0]?.with_check).not.toContain('app.invitation_token')
    expect(
      indexes.rows.some(
        (row) => row.indexdef.includes('UNIQUE') && row.indexdef.includes('"organizationId"'),
      ),
    ).toBe(true)
  })

  it('every tenant table is protected by row security', async () => {
    const unprotected = await withOwnerClient((client) =>
      findUnprotectedTenantTables(client, workerSchema()),
    )

    expect(unprotected).toEqual([])
  })

  it('flags a tenant table without row security', async () => {
    const tables = await withProbeSchema('rls', async (client, probe) => {
      const create = (name: string) =>
        client.query(
          `CREATE TABLE "${probe}"."${name}" (id uuid PRIMARY KEY, "organizationId" uuid)`,
        )
      const policy = (name: string) =>
        client.query(
          `CREATE POLICY tenant_isolation ON "${probe}"."${name}" USING (true) WITH CHECK (true)`,
        )
      // One synthetic table per missing clause, plus a fully protected control.
      await create('Open')
      await create('NoForce')
      await client.query(`ALTER TABLE "${probe}"."NoForce" ENABLE ROW LEVEL SECURITY`)
      await policy('NoForce')
      await create('NoEnable')
      await client.query(`ALTER TABLE "${probe}"."NoEnable" FORCE ROW LEVEL SECURITY`)
      await policy('NoEnable')
      await create('NoPolicy')
      await client.query(`ALTER TABLE "${probe}"."NoPolicy" ENABLE ROW LEVEL SECURITY`)
      await client.query(`ALTER TABLE "${probe}"."NoPolicy" FORCE ROW LEVEL SECURITY`)
      await create('Protected')
      await client.query(`ALTER TABLE "${probe}"."Protected" ENABLE ROW LEVEL SECURITY`)
      await client.query(`ALTER TABLE "${probe}"."Protected" FORCE ROW LEVEL SECURITY`)
      await policy('Protected')
      await client.query(`CREATE TABLE "${probe}"."NoTenant" (id uuid PRIMARY KEY)`)
      return findUnprotectedTenantTables(client, probe)
    })

    expect(tables).toEqual(['NoEnable', 'NoForce', 'NoPolicy', 'Open'])
  })

  it('foreign keys to unguarded tables never cascade', async () => {
    const real = await withOwnerClient((client) =>
      findCascadingForeignKeysToUnguarded(client, workerSchema()),
    )
    const synthetic = await withProbeSchema('fk', async (client, probe) => {
      await client.query(`CREATE TABLE "${probe}"."Root" (id uuid PRIMARY KEY)`)
      const child = (name: string, actions: string) =>
        client.query(
          `CREATE TABLE "${probe}"."${name}" (id uuid PRIMARY KEY, "organizationId" uuid,
             CONSTRAINT "${name}_fkey" FOREIGN KEY ("organizationId")
             REFERENCES "${probe}"."Root"(id) ${actions})`,
        )
      await child('DeleteCascade', 'ON DELETE CASCADE ON UPDATE RESTRICT')
      await child('UpdateCascade', 'ON DELETE RESTRICT ON UPDATE CASCADE')
      await child('SetNull', 'ON DELETE SET NULL ON UPDATE RESTRICT')
      // SET DEFAULT would move the rows into the tenant of the deleting transaction.
      await child('SetDefault', 'ON DELETE SET DEFAULT ON UPDATE RESTRICT')
      await child('UpdateSetNull', 'ON DELETE RESTRICT ON UPDATE SET NULL')
      await child('UpdateSetDefault', 'ON DELETE RESTRICT ON UPDATE SET DEFAULT')
      await child('Restricted', 'ON DELETE RESTRICT ON UPDATE RESTRICT')
      await child('NoAction', '')
      return findCascadingForeignKeysToUnguarded(client, probe)
    })

    expect(real).toEqual([])
    expect(synthetic).toEqual([
      'DeleteCascade_fkey',
      'SetDefault_fkey',
      'SetNull_fkey',
      'UpdateCascade_fkey',
      'UpdateSetDefault_fkey',
      'UpdateSetNull_fkey',
    ])
  })

  it('every unique index of a tenant table includes organizationId', async () => {
    const real = await withOwnerClient((client) =>
      findUniqueIndexesWithoutTenant(client, workerSchema()),
    )
    const synthetic = await withProbeSchema('unique', async (client, probe) => {
      await client.query(
        `CREATE TABLE "${probe}"."Client" (id uuid PRIMARY KEY, "organizationId" uuid, email text)`,
      )
      await client.query(
        `CREATE UNIQUE INDEX "Client_tenant_email_key" ON "${probe}"."Client" ("organizationId", email)`,
      )
      await client.query(`CREATE UNIQUE INDEX "Client_email_key" ON "${probe}"."Client" (email)`)
      return findUniqueIndexesWithoutTenant(client, probe)
    })

    expect(real).toEqual([])
    expect(synthetic).toEqual(['Client_email_key'])
  })
})

// ADR-004: every relation between two tenant-scoped models (models with `organizationId`) references
// `(id, organizationId)`, so the database itself rejects a row from another tenant.

type Field = { name: string; type: string; relationFields: string[] | undefined }

function parseModels(schema: string): Map<string, Field[]> {
  const models = new Map<string, Field[]>()
  for (const [, name, body] of schema.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)) {
    if (name === undefined || body === undefined) continue
    const fields = body
      .split('\n')
      .map((line) => line.replace(/\/\/.*$/, '').trim())
      .filter((line) => /^\w/.test(line))
      .map((line) => {
        const [fieldName = '', type = ''] = line.split(/\s+/)
        const relationFields = line.match(/@relation\([^)]*fields:\s*\[([^\]]*)\]/)?.[1]
        return {
          name: fieldName,
          type: type.replace(/[?[\]]/g, ''),
          relationFields: relationFields?.split(',').map((field) => field.trim()),
        }
      })
    models.set(name, fields)
  }
  return models
}

function findSimpleTenantRelations(schema: string): string[] {
  const models = parseModels(schema)
  const tenantScoped = new Set(
    [...models]
      .filter(([, fields]) => fields.some((f) => f.name === 'organizationId'))
      .map(([n]) => n),
  )
  const violations: string[] = []
  for (const [model, fields] of models) {
    if (!tenantScoped.has(model)) continue
    for (const field of fields) {
      // The side without `fields` is the back-relation; the owning side carries the foreign key.
      if (!tenantScoped.has(field.type) || field.relationFields === undefined) continue
      if (!field.relationFields.includes('organizationId'))
        violations.push(`${model}.${field.name}`)
    }
  }
  return violations
}

describe('Member', () => {
  // ADR-011: commission is out of the MVP, so the column is dropped by a migration.
  it('Member carries no commission column', async () => {
    const columns = await withOwnerClient(async (client) => {
      const { rows } = await client.query<{ column: string }>(
        `SELECT column_name AS column FROM information_schema.columns
          WHERE table_schema = $1 AND table_name = 'Member'`,
        [workerSchema()],
      )
      return rows.map((row) => row.column)
    })

    expect(columns).not.toContain('commissionSplitBp')
    expect(columns).toEqual(
      expect.arrayContaining([
        'id',
        'organizationId',
        'userId',
        'role',
        'active',
        'createdAt',
        'updatedAt',
      ]),
    )
  })

  // ADR-016: the MVP has three roles; OWNER and VIEWER left the enum.
  it('Role holds only ADMIN, MANAGER and COMMERCIAL', async () => {
    const { rows } = await withOwnerClient((client) =>
      client.query<{ label: string }>(
        `SELECT e.enumlabel AS label
           FROM pg_enum e
           JOIN pg_type t ON t.oid = e.enumtypid
           JOIN pg_namespace n ON n.oid = t.typnamespace
          WHERE n.nspname = $1 AND t.typname = 'Role'
          ORDER BY e.enumsortorder`,
        [workerSchema()],
      ),
    )

    expect(rows.map((row) => row.label)).toEqual(['ADMIN', 'MANAGER', 'COMMERCIAL'])
  })

  // "At least one active ADMIN" is enforced by the use case; the single-OWNER index is gone.
  it('has no Member_one_owner index', async () => {
    const { rows } = await withOwnerClient((client) =>
      client.query<{ name: string }>(
        `SELECT indexname AS name FROM pg_indexes
          WHERE schemaname = $1 AND tablename = 'Member'`,
        [workerSchema()],
      ),
    )

    expect(rows.map((row) => row.name)).not.toContain('Member_one_owner')
    expect(rows.map((row) => row.name)).toContain('Member_organizationId_userId_key')
  })
})

describe('Organization', () => {
  // ADR-014: the public chat key resolves the tenant, so no two organizations share one.
  it('publicChatKey is unique across organizations', async () => {
    const schema = workerSchema()
    const key = randomBytes(16).toString('hex')
    const insert = (client: pg.Client) =>
      client.query(
        `INSERT INTO "${schema}"."Organization" ("id", "name", "slug", "publicChatKey", "updatedAt")
         VALUES ($1, 'Chave', $2, $3, now())`,
        [randomUUID(), `chave-${randomUUID()}`, key],
      )

    const error = await withOwnerClient(async (client) => {
      await insert(client)
      return insert(client).then(
        () => undefined,
        (reason: unknown) => reason,
      )
    })

    expect(error).toMatchObject({ code: '23505', constraint: 'Organization_publicChatKey_key' })

    const missing = await withOwnerClient((client) =>
      client
        .query(
          `INSERT INTO "${schema}"."Organization" ("id", "name", "slug", "updatedAt")
           VALUES ($1, 'Sem chave', $2, now())`,
          [randomUUID(), `sem-chave-${randomUUID()}`],
        )
        .then(
          () => undefined,
          (reason: unknown) => reason,
        ),
    )
    expect(missing).toMatchObject({ code: '23502', column: 'publicChatKey' })
  })
})

describe('tenant-scoped relations', () => {
  it('every relation between tenant-scoped models uses a composite foreign key', () => {
    const schema = readFileSync(new URL('../prisma/schema.prisma', import.meta.url), 'utf8')

    expect(findSimpleTenantRelations(schema)).toEqual([])
  })

  it('flags a relation between tenant-scoped models without organizationId', () => {
    const schema = `
model Organization {
  id String @id
}

model Product {
  id             String @id
  organizationId String
  items          Item[]

  @@unique([id, organizationId])
}

model Item {
  id             String       @id
  organizationId String
  productId      String
  organization   Organization @relation(fields: [organizationId], references: [id])
  product        Product      @relation(fields: [productId], references: [id]) // simple FK
  sibling        Item?        @relation("Siblings", fields: [siblingId, organizationId], references: [id, organizationId])
  siblingId      String?
  siblings       Item[]       @relation("Siblings")
}
`

    expect(findSimpleTenantRelations(schema)).toEqual(['Item.product'])
  })
})

describe('identity tables', () => {
  it('identity tables carry no tenant column', async () => {
    const identity = ['Account', 'RateLimit', 'Session', 'TwoFactor', 'User', 'Verification']
    const { rows } = await withOwnerClient((client) =>
      client.query<{ table: string; tenant: boolean }>(
        `SELECT c.relname AS table,
                EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = c.oid
                         AND a.attname = 'organizationId' AND NOT a.attisdropped) AS tenant
           FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname = $1 AND c.relkind = 'r' AND c.relname = ANY ($2)
          ORDER BY 1`,
        [workerSchema(), identity],
      ),
    )

    // User-level tables (ADR-003): outside row level security, so no tenant column (ADR-004).
    expect(rows).toEqual(identity.map((table) => ({ table, tenant: false })))
  })

  it('forgets the last active organization when it is deleted', async () => {
    const remembered = await withOwnerClient(async (client) => {
      const schema = workerSchema()
      const {
        rows: [organization],
      } = await client.query<{ id: string }>(
        `INSERT INTO "${schema}"."Organization" (id, name, slug, "publicChatKey", "updatedAt")
         VALUES (gen_random_uuid(), 'Apagada', gen_random_uuid()::text,
                 replace(gen_random_uuid()::text, '-', ''), now()) RETURNING id`,
      )
      const {
        rows: [user],
      } = await client.query<{ id: string }>(
        `INSERT INTO "${schema}"."User" (id, name, email, "updatedAt", "lastActiveOrganizationId")
         VALUES (gen_random_uuid(), 'Maria', gen_random_uuid()::text || '@example.com', now(), $1)
         RETURNING id`,
        [organization?.id],
      )
      await client.query(`DELETE FROM "${schema}"."Organization" WHERE id = $1`, [organization?.id])
      const { rows } = await client.query<{ last: string | null }>(
        `SELECT "lastActiveOrganizationId" AS last FROM "${schema}"."User" WHERE id = $1`,
        [user?.id],
      )
      await client.query(`DELETE FROM "${schema}"."User" WHERE id = $1`, [user?.id])
      return rows
    })

    // org-web door 4: the row stays, the choice goes (ON DELETE SET NULL).
    expect(remembered).toEqual([{ last: null }])
  })
})

// Seeds, as the owner, one organization and `users` users in `schema`.
async function seedOrganizationWithUsers(client: pg.Client, schema: string, users: number) {
  const organizationId = randomUUID()
  await client.query(
    `INSERT INTO "${schema}"."Organization" (id, name, slug, "publicChatKey", "updatedAt")
     VALUES ($1, 'Semente', $2, replace(gen_random_uuid()::text, '-', ''), now())`,
    [organizationId, `semente-${organizationId}`],
  )
  const userIds: string[] = []
  for (let index = 0; index < users; index++) {
    const userId = randomUUID()
    await client.query(
      `INSERT INTO "${schema}"."User" (id, name, email, "updatedAt")
       VALUES ($1, 'Ator', $2, now())`,
      [userId, `${userId}@example.com`],
    )
    userIds.push(userId)
  }
  return { organizationId, userIds }
}

const AUDIT_ACTORS_MIGRATION = '20260924150000_audit_actors'

describe('AuditLog actor', () => {
  // audit-actors door 1: USER carries the user, AI and SYSTEM never do.
  it('ties the audit actor type to the actor user', async () => {
    const schema = workerSchema()
    const outcomes = await withOwnerClient(async (client) => {
      const {
        organizationId,
        userIds: [userId],
      } = await seedOrganizationWithUsers(client, schema, 1)
      const insert = (actorType: string, actorUserId: string | null) =>
        client
          .query(
            `INSERT INTO "${schema}"."AuditLog"
               (id, "organizationId", "actorType", "actorUserId", action, "entityId", changes)
             VALUES ($1, $2, $3::"${schema}"."AuditActorType", $4, 'test', $1, '{}')`,
            [randomUUID(), organizationId, actorType, actorUserId],
          )
          .then(
            () => 'ok',
            (error: { code?: string; constraint?: string }) =>
              `${error.code} ${error.constraint ?? ''}`.trim(),
          )
      return {
        userWithUser: await insert('USER', userId ?? null),
        userWithoutUser: await insert('USER', null),
        systemWithoutUser: await insert('SYSTEM', null),
        systemWithUser: await insert('SYSTEM', userId ?? null),
        aiWithoutUser: await insert('AI', null),
        aiWithUser: await insert('AI', userId ?? null),
      }
    })

    expect(outcomes).toEqual({
      userWithUser: 'ok',
      userWithoutUser: '23514 AuditLog_actor_check',
      systemWithoutUser: 'ok',
      systemWithUser: '23514 AuditLog_actor_check',
      aiWithoutUser: 'ok',
      aiWithUser: '23514 AuditLog_actor_check',
    })
  })

  it('backfills existing audit rows as user actors', async () => {
    const result = await withSchemaBefore(
      'audit',
      AUDIT_ACTORS_MIGRATION,
      async (client, apply, schema) => {
        const {
          organizationId,
          userIds: [first, second],
        } = await seedOrganizationWithUsers(client, schema, 2)
        await client.query(
          `INSERT INTO "AuditLog" (id, "organizationId", "actorUserId", action, "entityId", changes)
           VALUES ($1, $3, $4, 'member.update', $1, '{}'), ($2, $3, $5, 'member.update', $2, '{}')`,
          [randomUUID(), randomUUID(), organizationId, first, second],
        )
        await apply()
        const { rows } = await client.query<{ actorType: string; actorUserId: string }>(
          `SELECT "actorType", "actorUserId" FROM "AuditLog" ORDER BY "actorUserId"`,
        )
        return { rows, expected: [first, second].sort() }
      },
    )

    expect(result.rows).toEqual(
      result.expected.map((actorUserId) => ({ actorType: 'USER', actorUserId })),
    )
  })

  it('requires an explicit audit actor type', async () => {
    const schema = workerSchema()
    const { missing, columns } = await withOwnerClient(async (client) => {
      const {
        organizationId,
        userIds: [userId],
      } = await seedOrganizationWithUsers(client, schema, 1)
      const missing = await client
        .query(
          `INSERT INTO "${schema}"."AuditLog"
             (id, "organizationId", "actorUserId", action, "entityId", changes)
           VALUES ($1, $2, $3, 'test', $1, '{}')`,
          [randomUUID(), organizationId, userId],
        )
        .then(
          () => undefined,
          (reason: unknown) => reason,
        )
      const { rows: columns } = await client.query<{
        column: string
        default: string | null
        nullable: string
      }>(
        `SELECT column_name AS column, column_default AS default, is_nullable AS nullable
           FROM information_schema.columns
          WHERE table_schema = $1 AND table_name = 'AuditLog'
            AND column_name IN ('actorType', 'actorUserId')
          ORDER BY column_name`,
        [schema],
      )
      return { missing, columns }
    })

    expect(missing).toMatchObject({ code: '23502', column: 'actorType' })
    expect(columns).toEqual([
      { column: 'actorType', default: null, nullable: 'NO' },
      { column: 'actorUserId', default: null, nullable: 'YES' },
    ])
  })
})

const CONVERSATION_CORE_MIGRATION = '20260924160000_conversation_core'

// Seeds organizations in a schema built by the migrations before the conversation core. Under a
// non-superuser owner, FORCE applies: each insert needs the organization's own tenant.
async function seedOrganizations(client: pg.Client, count: number) {
  const ids: string[] = []
  for (let index = 0; index < count; index++) {
    const id = randomUUID()
    await client.query(`SELECT set_config('app.tenant_id', $1, false)`, [id])
    await client.query(
      `INSERT INTO "Organization" (id, name, slug, "publicChatKey", "updatedAt")
       VALUES ($1, 'Existente', $2, replace(gen_random_uuid()::text, '-', ''), now())`,
      [id, `existente-${id}`],
    )
    ids.push(id)
  }
  await client.query(`SELECT set_config('app.tenant_id', '', false)`)
  return ids
}

// Read as the superuser, which sees every row.
async function channelsBySchema(client: pg.Client, schema: string) {
  await client.query('RESET ROLE')
  const { rows } = await client.query<{ organizationId: string; kind: string; name: string }>(
    `SELECT "organizationId", kind, name FROM "${schema}"."Channel" ORDER BY "organizationId"`,
  )
  return rows
}

async function forcedRowSecurity(client: pg.Client, schema: string, tables: string[]) {
  const { rows } = await client.query<{ table: string; forced: boolean }>(
    `SELECT c.relname AS table,
            c.relrowsecurity AND c.relforcerowsecurity AND EXISTS (
              SELECT 1 FROM pg_policies p
               WHERE p.schemaname = n.nspname AND p.tablename = c.relname
                 AND p.policyname = 'tenant_isolation') AS forced
       FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relname = ANY ($2)
      ORDER BY 1`,
    [schema, tables],
  )
  return rows
}

const probeOwner = () => `${workerSchema()}_owner`

describe('default web chat backfill', () => {
  it('backfills one web chat channel per organization under forced row security', async () => {
    const { channels, organizations } = await withSchemaBefore(
      'channel_rls',
      CONVERSATION_CORE_MIGRATION,
      async (client, apply, schema) => {
        const organizations = await seedOrganizations(client, 3)
        await apply()
        return { channels: await channelsBySchema(client, schema), organizations }
      },
      { owner: probeOwner() },
    )

    expect(channels).toEqual(
      [...organizations]
        .sort()
        .map((organizationId) => ({ organizationId, kind: 'WEB_CHAT', name: 'Web Chat' })),
    )
  })

  it('backfills one web chat channel per organization as a superuser owner', async () => {
    const { channels, organizations } = await withSchemaBefore(
      'channel_super',
      CONVERSATION_CORE_MIGRATION,
      async (client, apply, schema) => {
        const organizations = await seedOrganizations(client, 3)
        await apply()
        return { channels: await channelsBySchema(client, schema), organizations }
      },
    )

    expect(channels).toEqual(
      [...organizations]
        .sort()
        .map((organizationId) => ({ organizationId, kind: 'WEB_CHAT', name: 'Web Chat' })),
    )
  })

  it('keeps organization and channel row security forced after the backfill', async () => {
    const tables = ['Channel', 'Organization']
    const probe = await withSchemaBefore(
      'channel_force',
      CONVERSATION_CORE_MIGRATION,
      async (client, apply, schema) => {
        await seedOrganizations(client, 1)
        await apply()
        return forcedRowSecurity(client, schema, tables)
      },
      { owner: probeOwner() },
    )
    const worker = await withOwnerClient((client) =>
      forcedRowSecurity(client, workerSchema(), tables),
    )

    const expected = tables.map((table) => ({ table, forced: true }))
    expect(probe).toEqual(expected)
    expect(worker).toEqual(expected)
  })
})

// A tenant graph in the worker schema, inserted as the owner (superuser): an organization, two
// members, a channel, a contact and a conversation.
async function seedGraph(client: pg.Client) {
  const schema = workerSchema()
  const {
    organizationId,
    userIds: [memberUser = '', outsider = ''],
  } = await seedOrganizationWithUsers(client, schema, 2)
  await client.query(
    `INSERT INTO "${schema}"."Member" (id, "organizationId", "userId", role, "updatedAt")
     VALUES ($1, $2, $3, 'COMMERCIAL', now())`,
    [randomUUID(), organizationId, memberUser],
  )
  const channelId = randomUUID()
  await client.query(
    `INSERT INTO "${schema}"."Channel" (id, "organizationId", kind, name, "updatedAt")
     VALUES ($1, $2, 'WEB_CHAT', 'Web Chat', now())`,
    [channelId, organizationId],
  )
  const contactId = await insertContact(client, organizationId, `+55119${randomDigits(8)}`)
  const conversationId = randomUUID()
  await client.query(
    `INSERT INTO "${schema}"."Conversation"
       (id, "organizationId", "contactId", "channelId", status, handler, "updatedAt")
     VALUES ($1, $2, $3, $4, 'OPEN', 'QUEUE', now())`,
    [conversationId, organizationId, contactId, channelId],
  )
  return { schema, organizationId, memberUser, outsider, channelId, contactId, conversationId }
}

function randomDigits(length: number) {
  return Array.from({ length }, () => Math.floor(Math.random() * 10)).join('')
}

async function insertContact(
  client: pg.Client,
  organizationId: string,
  phoneE164: string,
  ownerId: string | null = null,
) {
  const id = randomUUID()
  await client.query(
    `INSERT INTO "${workerSchema()}"."Contact" (id, "organizationId", "phoneE164", "ownerId", "updatedAt")
     VALUES ($1, $2, $3, $4, now())`,
    [id, organizationId, phoneE164, ownerId],
  )
  return id
}

// The SQLSTATE and constraint of a failed statement, or 'ok'.
function outcome(query: Promise<unknown>) {
  return query.then(
    () => 'ok',
    (error: { code?: string; constraint?: string }) =>
      `${error.code} ${error.constraint ?? ''}`.trim(),
  )
}

describe('conversation tables', () => {
  it('allows one web chat channel per organization', async () => {
    const result = await withOwnerClient(async (client) => {
      const graph = await seedGraph(client)
      const other = await seedOrganizationWithUsers(client, graph.schema, 0)
      const insert = (organizationId: string) =>
        outcome(
          client.query(
            `INSERT INTO "${graph.schema}"."Channel" (id, "organizationId", kind, name, "updatedAt")
             VALUES ($1, $2, 'WEB_CHAT', 'Outro', now())`,
            [randomUUID(), organizationId],
          ),
        )
      return {
        second: await insert(graph.organizationId),
        other: await insert(other.organizationId),
      }
    })

    expect(result).toEqual({ second: '23505 Channel_one_web_chat', other: 'ok' })
  })

  it('stores contact phones only in e164', async () => {
    const result = await withOwnerClient(async (client) => {
      const { organizationId } = await seedGraph(client)
      const insert = (phone: string) => outcome(insertContact(client, organizationId, phone))
      return {
        noPlus: await insert('5511987654321'),
        leadingZero: await insert('+0511987654321'),
        tooLong: await insert('+55119876543210123'),
        valid: await insert('+5511987654321'),
      }
    })

    expect(result).toEqual({
      noPlus: '23514 Contact_phoneE164_check',
      leadingZero: '23514 Contact_phoneE164_check',
      tooLong: '23514 Contact_phoneE164_check',
      valid: 'ok',
    })
  })

  it('requires the contact owner to be a member of the organization', async () => {
    const result = await withOwnerClient(async (client) => {
      const graph = await seedGraph(client)
      // The outsider is a member of another organization only.
      const other = await seedOrganizationWithUsers(client, graph.schema, 0)
      await client.query(
        `INSERT INTO "${graph.schema}"."Member" (id, "organizationId", "userId", role, "updatedAt")
         VALUES ($1, $2, $3, 'COMMERCIAL', now())`,
        [randomUUID(), other.organizationId, graph.outsider],
      )
      const insert = (ownerId: string) =>
        outcome(insertContact(client, graph.organizationId, `+55119${randomDigits(8)}`, ownerId))
      return { outsider: await insert(graph.outsider), member: await insert(graph.memberUser) }
    })

    expect(result).toEqual({ outsider: '23503 Contact_organizationId_ownerId_fkey', member: 'ok' })
  })

  it('ties the conversation assignee and closing to its state', async () => {
    const result = await withOwnerClient(async (client) => {
      const graph = await seedGraph(client)
      const update = (set: string, values: unknown[] = []) =>
        outcome(
          client.query(`UPDATE "${graph.schema}"."Conversation" SET ${set} WHERE id = $1`, [
            graph.conversationId,
            ...values,
          ]),
        )
      return {
        outsiderAssignee: await update(`handler = 'HUMAN', "assigneeId" = $2`, [graph.outsider]),
        assigneeWithoutHuman: await update(`handler = 'QUEUE', "assigneeId" = $2`, [
          graph.memberUser,
        ]),
        humanWithoutAssignee: await update(`handler = 'HUMAN', "assigneeId" = NULL`),
        closedAtWhileOpen: await update(`status = 'OPEN', "closedAt" = now()`),
        closedWithoutClosedAt: await update(`status = 'CLOSED', "closedAt" = NULL`),
        memberAssignee: await update(`handler = 'HUMAN', "assigneeId" = $2`, [graph.memberUser]),
        closed: await update(`status = 'CLOSED', "closedAt" = now()`),
      }
    })

    expect(result).toEqual({
      outsiderAssignee: '23503 Conversation_organizationId_assigneeId_fkey',
      assigneeWithoutHuman: '23514 Conversation_assignee_check',
      humanWithoutAssignee: '23514 Conversation_assignee_check',
      closedAtWhileOpen: '23514 Conversation_closed_check',
      closedWithoutClosedAt: '23514 Conversation_closed_check',
      memberAssignee: 'ok',
      closed: 'ok',
    })
  })

  it('has the conversation unique indexes of adr-013', async () => {
    const definitions = await withOwnerClient(async (client) => {
      const { rows } = await client.query<{ name: string; definition: string }>(
        `SELECT indexname AS name, indexdef AS definition FROM pg_indexes
          WHERE schemaname = $1 AND tablename IN ('Channel', 'Contact', 'Conversation', 'Message')`,
        [workerSchema()],
      )
      // Drop the worker schema qualifier so the definitions read as in the migration.
      const qualifier = `${workerSchema()}.`
      return new Map(rows.map((row) => [row.name, row.definition.replaceAll(qualifier, '')]))
    })

    expect(definitions.get('Message_organizationId_conversationId_seq_key')).toBe(
      'CREATE UNIQUE INDEX "Message_organizationId_conversationId_seq_key" ON "Message" USING btree ("organizationId", "conversationId", seq)',
    )
    expect(definitions.get('Message_channel_externalId')).toBe(
      'CREATE UNIQUE INDEX "Message_channel_externalId" ON "Message" USING btree ("organizationId", "channelId", "externalId") WHERE ("externalId" IS NOT NULL)',
    )
    expect(definitions.get('Conversation_one_open')).toBe(
      `CREATE UNIQUE INDEX "Conversation_one_open" ON "Conversation" USING btree ("organizationId", "contactId", "channelId") WHERE (status <> 'CLOSED'::"ConversationStatus")`,
    )
    expect(definitions.get('Contact_organizationId_phoneE164_key')).toBe(
      'CREATE UNIQUE INDEX "Contact_organizationId_phoneE164_key" ON "Contact" USING btree ("organizationId", "phoneE164")',
    )
    expect(definitions.get('Channel_one_web_chat')).toBe(
      `CREATE UNIQUE INDEX "Channel_one_web_chat" ON "Channel" USING btree ("organizationId") WHERE (kind = 'WEB_CHAT'::"ChannelKind")`,
    )
  })

  it('enforces the conversation unique indexes', async () => {
    const result = await withOwnerClient(async (client) => {
      const graph = await seedGraph(client)
      const conversation = (status: string) =>
        outcome(
          client.query(
            `INSERT INTO "${graph.schema}"."Conversation"
               (id, "organizationId", "contactId", "channelId", status, handler, "closedAt", "updatedAt")
             VALUES ($1, $2, $3, $4, $5::"${graph.schema}"."ConversationStatus", 'QUEUE',
                     CASE WHEN $5 = 'CLOSED' THEN now() END, now())`,
            [randomUUID(), graph.organizationId, graph.contactId, graph.channelId, status],
          ),
        )
      const message = (seq: number, externalId: string | null) =>
        outcome(
          client.query(
            `INSERT INTO "${graph.schema}"."Message"
               (id, "organizationId", "conversationId", "channelId", seq, direction, author, kind,
                text, "externalId", "sentAt")
             VALUES ($1, $2, $3, $4, $5, 'INBOUND', 'CONTACT', 'TEXT', 'oi', $6, now())`,
            [
              randomUUID(),
              graph.organizationId,
              graph.conversationId,
              graph.channelId,
              seq,
              externalId,
            ],
          ),
        )
      return {
        secondOpen: await conversation('OPEN'),
        closedBesideOpen: await conversation('CLOSED'),
        firstExternal: await message(1, 'wa-1'),
        sameExternal: await message(2, 'wa-1'),
        firstNull: await message(3, null),
        secondNull: await message(4, null),
        sameSeq: await message(4, 'wa-2'),
      }
    })

    expect(result).toEqual({
      secondOpen: '23505 Conversation_one_open',
      closedBesideOpen: 'ok',
      firstExternal: 'ok',
      sameExternal: '23505 Message_channel_externalId',
      firstNull: 'ok',
      secondNull: 'ok',
      sameSeq: '23505 Message_organizationId_conversationId_seq_key',
    })
  })

  it('protects the conversation tables with tenant_isolation', async () => {
    const tables = ['Channel', 'Contact', 'Conversation', 'Message']
    const { forced, policies } = await withOwnerClient(async (client) => ({
      forced: await forcedRowSecurity(client, workerSchema(), tables),
      policies: (
        await client.query<{ table: string; qual: string; check: string }>(
          `SELECT tablename AS table, qual, with_check AS check FROM pg_policies
            WHERE schemaname = $1 AND tablename = ANY ($2) AND policyname = 'tenant_isolation'
            ORDER BY 1`,
          [workerSchema(), tables],
        )
      ).rows,
    }))

    expect(forced).toEqual(tables.map((table) => ({ table, forced: true })))
    expect(policies.map((policy) => policy.table)).toEqual(tables)
    for (const policy of policies) {
      expect(policy.qual, policy.table).toContain('app.tenant_id')
      expect(policy.check, policy.table).toContain('app.tenant_id')
    }
  })

  it('keeps a message consistent with its direction, author, kind and conversation', async () => {
    const result = await withOwnerClient(async (client) => {
      const graph = await seedGraph(client)
      const otherChannel = await seedOrganizationWithUsers(client, graph.schema, 0).then(() =>
        randomUUID(),
      )
      let seq = 0
      const insert = (columns: {
        direction: string
        author: string
        authorUserId?: string | null
        kind?: string
        text?: string | null
        deliveryStatus?: string | null
        channelId?: string
      }) =>
        outcome(
          client.query(
            `INSERT INTO "${graph.schema}"."Message"
               (id, "organizationId", "conversationId", "channelId", seq, direction, author,
                "authorUserId", kind, text, "deliveryStatus", "sentAt")
             VALUES ($1, $2, $3, $4, $5, $6::"${graph.schema}"."MessageDirection",
                     $7::"${graph.schema}"."MessageAuthor", $8, $9::"${graph.schema}"."MessageKind",
                     $10, $11::"${graph.schema}"."DeliveryStatus", now())`,
            [
              randomUUID(),
              graph.organizationId,
              graph.conversationId,
              columns.channelId ?? graph.channelId,
              ++seq,
              columns.direction,
              columns.author,
              columns.authorUserId ?? null,
              columns.kind ?? 'TEXT',
              columns.text === undefined ? 'oi' : columns.text,
              columns.deliveryStatus ?? null,
            ],
          ),
        )
      return {
        inboundFromSystem: await insert({ direction: 'INBOUND', author: 'SYSTEM' }),
        outboundFromContact: await insert({
          direction: 'OUTBOUND',
          author: 'CONTACT',
          deliveryStatus: 'SENT',
        }),
        inboundDelivered: await insert({
          direction: 'INBOUND',
          author: 'CONTACT',
          deliveryStatus: 'SENT',
        }),
        outboundUndelivered: await insert({ direction: 'OUTBOUND', author: 'SYSTEM' }),
        humanWithoutUser: await insert({
          direction: 'OUTBOUND',
          author: 'HUMAN',
          deliveryStatus: 'SENT',
        }),
        systemWithUser: await insert({
          direction: 'OUTBOUND',
          author: 'SYSTEM',
          authorUserId: graph.memberUser,
          deliveryStatus: 'SENT',
        }),
        textWithoutText: await insert({ direction: 'INBOUND', author: 'CONTACT', text: null }),
        unsupportedWithText: await insert({
          direction: 'INBOUND',
          author: 'CONTACT',
          kind: 'UNSUPPORTED',
        }),
        otherChannel: await insert({
          direction: 'INBOUND',
          author: 'CONTACT',
          channelId: otherChannel,
        }),
        valid: await insert({ direction: 'INBOUND', author: 'CONTACT' }),
      }
    })

    expect(result).toEqual({
      inboundFromSystem: '23514 Message_direction_check',
      outboundFromContact: '23514 Message_direction_check',
      inboundDelivered: '23514 Message_delivery_check',
      outboundUndelivered: '23514 Message_delivery_check',
      humanWithoutUser: '23514 Message_author_user_check',
      systemWithUser: '23514 Message_author_user_check',
      textWithoutText: '23514 Message_text_check',
      unsupportedWithText: '23514 Message_text_check',
      otherChannel: '23503 Message_conversationId_channelId_organizationId_fkey',
      valid: 'ok',
    })
  })
})
