import { readFileSync } from 'node:fs'
import type pg from 'pg'
import { beforeAll, describe, expect, it } from 'vitest'
import { prepareTestDatabase, withOwnerClient, workerSchema } from './setup-db.ts'

// ADR-004: every table with `organizationId` has row level security enabled and forced with the
// `tenant_isolation` policy, and its unique indexes include the tenant (integrity checks bypass RLS).
// Checked in the PostgreSQL catalog of this worker's schema, which the real migrations built.

async function findUnprotectedTenantTables(client: pg.Client, schema: string) {
  const { rows } = await client.query<{ table: string }>(
    `SELECT c.relname AS table
       FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = $1 AND c.relkind = 'r'
        AND EXISTS (SELECT 1 FROM pg_attribute a
                     WHERE a.attrelid = c.oid AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND NOT (c.relrowsecurity AND c.relforcerowsecurity AND EXISTS (
              SELECT 1 FROM pg_policies p
               WHERE p.schemaname = n.nspname AND p.tablename = c.relname
                 AND p.policyname = 'tenant_isolation'))
      ORDER BY 1`,
    [schema],
  )
  return rows.map((row) => row.table)
}

// Primary keys are excluded: ids are generated by the server (UUID v7), never taken from input.
async function findUniqueIndexesWithoutTenant(client: pg.Client, schema: string) {
  const { rows } = await client.query<{ index: string }>(
    `SELECT i.relname AS index
       FROM pg_index x
       JOIN pg_class t ON t.oid = x.indrelid
       JOIN pg_class i ON i.oid = x.indexrelid
       JOIN pg_namespace n ON n.oid = t.relnamespace
      WHERE n.nspname = $1 AND x.indisunique AND NOT x.indisprimary
        AND EXISTS (SELECT 1 FROM pg_attribute a
                     WHERE a.attrelid = t.oid AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND NOT EXISTS (SELECT 1 FROM pg_attribute a
                         WHERE a.attrelid = t.oid AND a.attname = 'organizationId'
                           AND a.attnum = ANY (x.indkey))
      ORDER BY 1`,
    [schema],
  )
  return rows.map((row) => row.index)
}

// A cascade runs as the table owner, so it ignores row security (ADR-004): from a tenant table to a
// table without organizationId, deletes and updates must not propagate.
async function findCascadingForeignKeysToUnguarded(client: pg.Client, schema: string) {
  const { rows } = await client.query<{ fk: string }>(
    `SELECT con.conname AS fk
       FROM pg_constraint con
       JOIN pg_class child ON child.oid = con.conrelid
       JOIN pg_class parent ON parent.oid = con.confrelid
       JOIN pg_namespace n ON n.oid = child.relnamespace
      WHERE n.nspname = $1 AND con.contype = 'f'
        AND EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = child.oid
                     AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND NOT EXISTS (SELECT 1 FROM pg_attribute a WHERE a.attrelid = parent.oid
                         AND a.attname = 'organizationId' AND NOT a.attisdropped)
        AND (con.confdeltype NOT IN ('r', 'a') OR con.confupdtype NOT IN ('r', 'a'))
      ORDER BY 1`,
    [schema],
  )
  return rows.map((row) => row.fk)
}

// A throwaway schema next to the worker's, dropped afterwards.
function withProbeSchema<T>(label: string, run: (client: pg.Client, probe: string) => Promise<T>) {
  const probe = `${workerSchema()}_${label}_probe`
  return withOwnerClient(async (client) => {
    await client.query(`DROP SCHEMA IF EXISTS "${probe}" CASCADE`)
    await client.query(`CREATE SCHEMA "${probe}"`)
    try {
      return await run(client, probe)
    } finally {
      await client.query(`DROP SCHEMA "${probe}" CASCADE`)
    }
  })
}

beforeAll(() => prepareTestDatabase())

describe('tenant tables', () => {
  it('every tenant table is protected by row security', async () => {
    const unprotected = await withOwnerClient((client) =>
      findUnprotectedTenantTables(client, workerSchema()),
    )

    expect(unprotected).toEqual([])
  })

  it('flags a tenant table without row security', async () => {
    const tables = await withProbeSchema('rls', async (client, probe) => {
      const create = (name: string) =>
        client.query(
          `CREATE TABLE "${probe}"."${name}" (id uuid PRIMARY KEY, "organizationId" uuid)`,
        )
      const policy = (name: string) =>
        client.query(
          `CREATE POLICY tenant_isolation ON "${probe}"."${name}" USING (true) WITH CHECK (true)`,
        )
      // One synthetic table per missing clause, plus a fully protected control.
      await create('Open')
      await create('NoForce')
      await client.query(`ALTER TABLE "${probe}"."NoForce" ENABLE ROW LEVEL SECURITY`)
      await policy('NoForce')
      await create('NoEnable')
      await client.query(`ALTER TABLE "${probe}"."NoEnable" FORCE ROW LEVEL SECURITY`)
      await policy('NoEnable')
      await create('NoPolicy')
      await client.query(`ALTER TABLE "${probe}"."NoPolicy" ENABLE ROW LEVEL SECURITY`)
      await client.query(`ALTER TABLE "${probe}"."NoPolicy" FORCE ROW LEVEL SECURITY`)
      await create('Protected')
      await client.query(`ALTER TABLE "${probe}"."Protected" ENABLE ROW LEVEL SECURITY`)
      await client.query(`ALTER TABLE "${probe}"."Protected" FORCE ROW LEVEL SECURITY`)
      await policy('Protected')
      await client.query(`CREATE TABLE "${probe}"."NoTenant" (id uuid PRIMARY KEY)`)
      return findUnprotectedTenantTables(client, probe)
    })

    expect(tables).toEqual(['NoEnable', 'NoForce', 'NoPolicy', 'Open'])
  })

  it('foreign keys to unguarded tables never cascade', async () => {
    const real = await withOwnerClient((client) =>
      findCascadingForeignKeysToUnguarded(client, workerSchema()),
    )
    const synthetic = await withProbeSchema('fk', async (client, probe) => {
      await client.query(`CREATE TABLE "${probe}"."Root" (id uuid PRIMARY KEY)`)
      const child = (name: string, actions: string) =>
        client.query(
          `CREATE TABLE "${probe}"."${name}" (id uuid PRIMARY KEY, "organizationId" uuid,
             CONSTRAINT "${name}_fkey" FOREIGN KEY ("organizationId")
             REFERENCES "${probe}"."Root"(id) ${actions})`,
        )
      await child('DeleteCascade', 'ON DELETE CASCADE ON UPDATE RESTRICT')
      await child('UpdateCascade', 'ON DELETE RESTRICT ON UPDATE CASCADE')
      await child('SetNull', 'ON DELETE SET NULL ON UPDATE RESTRICT')
      await child('Restricted', 'ON DELETE RESTRICT ON UPDATE RESTRICT')
      await child('NoAction', '')
      return findCascadingForeignKeysToUnguarded(client, probe)
    })

    expect(real).toEqual([])
    expect(synthetic).toEqual(['DeleteCascade_fkey', 'SetNull_fkey', 'UpdateCascade_fkey'])
  })

  it('every unique index of a tenant table includes organizationId', async () => {
    const real = await withOwnerClient((client) =>
      findUniqueIndexesWithoutTenant(client, workerSchema()),
    )
    const synthetic = await withProbeSchema('unique', async (client, probe) => {
      await client.query(
        `CREATE TABLE "${probe}"."Client" (id uuid PRIMARY KEY, "organizationId" uuid, email text)`,
      )
      await client.query(
        `CREATE UNIQUE INDEX "Client_tenant_email_key" ON "${probe}"."Client" ("organizationId", email)`,
      )
      await client.query(`CREATE UNIQUE INDEX "Client_email_key" ON "${probe}"."Client" (email)`)
      return findUniqueIndexesWithoutTenant(client, probe)
    })

    expect(real).toEqual([])
    expect(synthetic).toEqual(['Client_email_key'])
  })
})

// ADR-004: every relation between two tenant-scoped models (models with `organizationId`) references
// `(id, organizationId)`, so the database itself rejects a row from another tenant.

type Field = { name: string; type: string; relationFields: string[] | undefined }

function parseModels(schema: string): Map<string, Field[]> {
  const models = new Map<string, Field[]>()
  for (const [, name, body] of schema.matchAll(/^model\s+(\w+)\s*\{([\s\S]*?)^\}/gm)) {
    if (name === undefined || body === undefined) continue
    const fields = body
      .split('\n')
      .map((line) => line.replace(/\/\/.*$/, '').trim())
      .filter((line) => /^\w/.test(line))
      .map((line) => {
        const [fieldName = '', type = ''] = line.split(/\s+/)
        const relationFields = line.match(/@relation\([^)]*fields:\s*\[([^\]]*)\]/)?.[1]
        return {
          name: fieldName,
          type: type.replace(/[?[\]]/g, ''),
          relationFields: relationFields?.split(',').map((field) => field.trim()),
        }
      })
    models.set(name, fields)
  }
  return models
}

function findSimpleTenantRelations(schema: string): string[] {
  const models = parseModels(schema)
  const tenantScoped = new Set(
    [...models]
      .filter(([, fields]) => fields.some((f) => f.name === 'organizationId'))
      .map(([n]) => n),
  )
  const violations: string[] = []
  for (const [model, fields] of models) {
    if (!tenantScoped.has(model)) continue
    for (const field of fields) {
      // The side without `fields` is the back-relation; the owning side carries the foreign key.
      if (!tenantScoped.has(field.type) || field.relationFields === undefined) continue
      if (!field.relationFields.includes('organizationId'))
        violations.push(`${model}.${field.name}`)
    }
  }
  return violations
}

describe('tenant-scoped relations', () => {
  it('every relation between tenant-scoped models uses a composite foreign key', () => {
    const schema = readFileSync(new URL('../prisma/schema.prisma', import.meta.url), 'utf8')

    expect(
      parseModels(schema)
        .get('Example')
        ?.some((f) => f.name === 'parent'),
    ).toBe(true)
    expect(findSimpleTenantRelations(schema)).toEqual([])
  })

  it('flags a relation between tenant-scoped models without organizationId', () => {
    const schema = `
model Organization {
  id String @id
}

model Product {
  id             String @id
  organizationId String
  items          Item[]

  @@unique([id, organizationId])
}

model Item {
  id             String       @id
  organizationId String
  productId      String
  organization   Organization @relation(fields: [organizationId], references: [id])
  product        Product      @relation(fields: [productId], references: [id]) // simple FK
  sibling        Item?        @relation("Siblings", fields: [siblingId, organizationId], references: [id, organizationId])
  siblingId      String?
  siblings       Item[]       @relation("Siblings")
}
`

    expect(findSimpleTenantRelations(schema)).toEqual(['Item.product'])
  })
})
