/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as TermsAcceptanceRouteImport } from './routes/terms-acceptance'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authTwoFactorRouteImport } from './routes/(auth)/two-factor'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as onboardingAcceptInvitationRouteImport } from './routes/(onboarding)/accept-invitation'
import { Route as onboardingOnboardingRouteImport } from './routes/(onboarding)/onboarding'
import { Route as onboardingSelectOrgRouteImport } from './routes/(onboarding)/select-org'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as CKeyRouteImport } from './routes/c.$key'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsOrganizationRouteImport } from './routes/_app/settings/organization'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAcceptanceRoute = TermsAcceptanceRouteImport.update({
  id: '/terms-acceptance',
  path: '/terms-acceptance',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authTwoFactorRoute = authTwoFactorRouteImport.update({
  id: '/(auth)/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingAcceptInvitationRoute =
  onboardingAcceptInvitationRouteImport.update({
    id: '/(onboarding)/accept-invitation',
    path: '/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const onboardingOnboardingRoute = onboardingOnboardingRouteImport.update({
  id: '/(onboarding)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingSelectOrgRoute = onboardingSelectOrgRouteImport.update({
  id: '/(onboarding)/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/(public)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/(public)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const CKeyRoute = CKeyRouteImport.update({
  id: '/c/$key',
  path: '/c/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/terms-acceptance': typeof TermsAcceptanceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/two-factor': typeof authTwoFactorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invitation': typeof onboardingAcceptInvitationRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/select-org': typeof onboardingSelectOrgRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/c/$key': typeof CKeyRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/security': typeof AppSettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/terms-acceptance': typeof TermsAcceptanceRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/two-factor': typeof authTwoFactorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invitation': typeof onboardingAcceptInvitationRoute
  '/onboarding': typeof onboardingOnboardingRoute
  '/select-org': typeof onboardingSelectOrgRoute
  '/privacy': typeof publicPrivacyRoute
  '/terms': typeof publicTermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/c/$key': typeof CKeyRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/organization': typeof AppSettingsOrganizationRoute
  '/settings/security': typeof AppSettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/terms-acceptance': typeof TermsAcceptanceRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/two-factor': typeof authTwoFactorRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(onboarding)/accept-invitation': typeof onboardingAcceptInvitationRoute
  '/(onboarding)/onboarding': typeof onboardingOnboardingRoute
  '/(onboarding)/select-org': typeof onboardingSelectOrgRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/terms': typeof publicTermsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/c/$key': typeof CKeyRoute
  '/(public)/': typeof publicIndexRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/organization': typeof AppSettingsOrganizationRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms-acceptance'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/accept-invitation'
    | '/onboarding'
    | '/select-org'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/inbox'
    | '/c/$key'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms-acceptance'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/two-factor'
    | '/verify-email'
    | '/accept-invitation'
    | '/onboarding'
    | '/select-org'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/inbox'
    | '/c/$key'
    | '/settings/members'
    | '/settings/organization'
    | '/settings/security'
  id:
    | '__root__'
    | '/_app'
    | '/terms-acceptance'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/two-factor'
    | '/(auth)/verify-email'
    | '/(onboarding)/accept-invitation'
    | '/(onboarding)/onboarding'
    | '/(onboarding)/select-org'
    | '/(public)/privacy'
    | '/(public)/terms'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/c/$key'
    | '/(public)/'
    | '/_app/settings/members'
    | '/_app/settings/organization'
    | '/_app/settings/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  TermsAcceptanceRoute: typeof TermsAcceptanceRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authTwoFactorRoute: typeof authTwoFactorRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  onboardingAcceptInvitationRoute: typeof onboardingAcceptInvitationRoute
  onboardingOnboardingRoute: typeof onboardingOnboardingRoute
  onboardingSelectOrgRoute: typeof onboardingSelectOrgRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicTermsRoute: typeof publicTermsRoute
  CKeyRoute: typeof CKeyRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-acceptance': {
      id: '/terms-acceptance'
      path: '/terms-acceptance'
      fullPath: '/terms-acceptance'
      preLoaderRoute: typeof TermsAcceptanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/two-factor': {
      id: '/(auth)/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof authTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/accept-invitation': {
      id: '/(onboarding)/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof onboardingAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/onboarding': {
      id: '/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof onboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/select-org': {
      id: '/(onboarding)/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof onboardingSelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/c/$key': {
      id: '/c/$key'
      path: '/c/$key'
      fullPath: '/c/$key'
      preLoaderRoute: typeof CKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/organization': {
      id: '/_app/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  TermsAcceptanceRoute: TermsAcceptanceRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authTwoFactorRoute: authTwoFactorRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  onboardingAcceptInvitationRoute: onboardingAcceptInvitationRoute,
  onboardingOnboardingRoute: onboardingOnboardingRoute,
  onboardingSelectOrgRoute: onboardingSelectOrgRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicTermsRoute: publicTermsRoute,
  CKeyRoute: CKeyRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
