/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPublicChat200,
  GetPublicChatSession200,
  ListPublicChatMessages200,
  ListPublicChatMessagesParams,
  SendPublicChatMessage200,
  SendPublicChatMessage201,
  SendPublicChatMessageBody,
  StartPublicChatSession201,
  StartPublicChatSessionBody
} from '../../model';

import { http } from '../../../lib/http';
import type { ErrorType } from '../../../lib/http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetPublicChatUrl = (key: string,) => {




  return `/api/public/chat/${key}`
}

export const getPublicChat = async (key: string, options?: Parameters<typeof http>[1]): Promise<GetPublicChat200> => {

  return http<GetPublicChat200>(getGetPublicChatUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPublicChatQueryKey = (key: string,) => {
    return [
    `/api/public/chat/${key}`
    ] as const;
    }


export const getGetPublicChatQueryOptions = <TData = Awaited<ReturnType<typeof getPublicChat>>, TError = ErrorType<unknown>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChat>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicChatQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicChat>>> = ({ signal }) => getPublicChat(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicChat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicChatQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicChat>>>
export type GetPublicChatQueryError = ErrorType<unknown>


export function useGetPublicChat<TData = Awaited<ReturnType<typeof getPublicChat>>, TError = ErrorType<unknown>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicChat>>,
          TError,
          Awaited<ReturnType<typeof getPublicChat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicChat<TData = Awaited<ReturnType<typeof getPublicChat>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicChat>>,
          TError,
          Awaited<ReturnType<typeof getPublicChat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicChat<TData = Awaited<ReturnType<typeof getPublicChat>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChat>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPublicChat<TData = Awaited<ReturnType<typeof getPublicChat>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChat>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicChatQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetPublicChatLogoUrl = (key: string,) => {




  return `/api/public/chat/${key}/logo`
}

export const getPublicChatLogo = async (key: string, options?: Parameters<typeof http>[1]): Promise<void> => {

  return http<void>(getGetPublicChatLogoUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPublicChatLogoQueryKey = (key: string,) => {
    return [
    `/api/public/chat/${key}/logo`
    ] as const;
    }


export const getGetPublicChatLogoQueryOptions = <TData = Awaited<ReturnType<typeof getPublicChatLogo>>, TError = ErrorType<unknown>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatLogo>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicChatLogoQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicChatLogo>>> = ({ signal }) => getPublicChatLogo(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicChatLogo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicChatLogoQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicChatLogo>>>
export type GetPublicChatLogoQueryError = ErrorType<unknown>


export function useGetPublicChatLogo<TData = Awaited<ReturnType<typeof getPublicChatLogo>>, TError = ErrorType<unknown>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatLogo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicChatLogo>>,
          TError,
          Awaited<ReturnType<typeof getPublicChatLogo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicChatLogo<TData = Awaited<ReturnType<typeof getPublicChatLogo>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatLogo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicChatLogo>>,
          TError,
          Awaited<ReturnType<typeof getPublicChatLogo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicChatLogo<TData = Awaited<ReturnType<typeof getPublicChatLogo>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatLogo>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPublicChatLogo<TData = Awaited<ReturnType<typeof getPublicChatLogo>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatLogo>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicChatLogoQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getStartPublicChatSessionUrl = (key: string,) => {




  return `/api/public/chat/${key}/sessions`
}

export const startPublicChatSession = async (key: string,
    startPublicChatSessionBody: StartPublicChatSessionBody, options?: Parameters<typeof http>[1]): Promise<StartPublicChatSession201> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<StartPublicChatSession201>(getStartPublicChatSessionUrl(key),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(startPublicChatSessionBody)
  }
);}





export const getStartPublicChatSessionMutationKey = () => ['startPublicChatSession'] as const;

export const getStartPublicChatSessionMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startPublicChatSession>>, TError,StartPublicChatSessionMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof startPublicChatSession>>, TError,StartPublicChatSessionMutationVariables, TContext> => {

const mutationKey = getStartPublicChatSessionMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startPublicChatSession>>, StartPublicChatSessionMutationVariables> = (props) => {
          const {key,data} = props ?? {};

          return  startPublicChatSession(key,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StartPublicChatSessionMutationResult = NonNullable<Awaited<ReturnType<typeof startPublicChatSession>>>
    export type StartPublicChatSessionMutationBody = StartPublicChatSessionBody
    export type StartPublicChatSessionMutationError = ErrorType<unknown>
    export type StartPublicChatSessionMutationVariables = {key: string;data: StartPublicChatSessionBody}

    export const useStartPublicChatSession = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startPublicChatSession>>, TError,StartPublicChatSessionMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startPublicChatSession>>,
        TError,
        StartPublicChatSessionMutationVariables,
        TContext
      > => {
      return useMutation(getStartPublicChatSessionMutationOptions(options), queryClient);
    }
    export const getGetPublicChatSessionUrl = (key: string,) => {




  return `/api/public/chat/${key}/session`
}

export const getPublicChatSession = async (key: string, options?: Parameters<typeof http>[1]): Promise<GetPublicChatSession200> => {

  return http<GetPublicChatSession200>(getGetPublicChatSessionUrl(key),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPublicChatSessionQueryKey = (key: string,) => {
    return [
    `/api/public/chat/${key}/session`
    ] as const;
    }


export const getGetPublicChatSessionQueryOptions = <TData = Awaited<ReturnType<typeof getPublicChatSession>>, TError = ErrorType<unknown>>(key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatSession>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicChatSessionQueryKey(key);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicChatSession>>> = ({ signal }) => getPublicChatSession(key, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicChatSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicChatSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicChatSession>>>
export type GetPublicChatSessionQueryError = ErrorType<unknown>


export function useGetPublicChatSession<TData = Awaited<ReturnType<typeof getPublicChatSession>>, TError = ErrorType<unknown>>(
 key: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicChatSession>>,
          TError,
          Awaited<ReturnType<typeof getPublicChatSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicChatSession<TData = Awaited<ReturnType<typeof getPublicChatSession>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicChatSession>>,
          TError,
          Awaited<ReturnType<typeof getPublicChatSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicChatSession<TData = Awaited<ReturnType<typeof getPublicChatSession>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatSession>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPublicChatSession<TData = Awaited<ReturnType<typeof getPublicChatSession>>, TError = ErrorType<unknown>>(
 key: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicChatSession>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicChatSessionQueryOptions(key,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getSendPublicChatMessageUrl = (key: string,) => {




  return `/api/public/chat/${key}/messages`
}

export const sendPublicChatMessage = async (key: string,
    sendPublicChatMessageBody: SendPublicChatMessageBody, options?: Parameters<typeof http>[1]): Promise<SendPublicChatMessage200 | SendPublicChatMessage201> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<SendPublicChatMessage200 | SendPublicChatMessage201>(getSendPublicChatMessageUrl(key),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(sendPublicChatMessageBody)
  }
);}





export const getSendPublicChatMessageMutationKey = () => ['sendPublicChatMessage'] as const;

export const getSendPublicChatMessageMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendPublicChatMessage>>, TError,SendPublicChatMessageMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof sendPublicChatMessage>>, TError,SendPublicChatMessageMutationVariables, TContext> => {

const mutationKey = getSendPublicChatMessageMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendPublicChatMessage>>, SendPublicChatMessageMutationVariables> = (props) => {
          const {key,data} = props ?? {};

          return  sendPublicChatMessage(key,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendPublicChatMessageMutationResult = NonNullable<Awaited<ReturnType<typeof sendPublicChatMessage>>>
    export type SendPublicChatMessageMutationBody = SendPublicChatMessageBody
    export type SendPublicChatMessageMutationError = ErrorType<unknown>
    export type SendPublicChatMessageMutationVariables = {key: string;data: SendPublicChatMessageBody}

    export const useSendPublicChatMessage = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendPublicChatMessage>>, TError,SendPublicChatMessageMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendPublicChatMessage>>,
        TError,
        SendPublicChatMessageMutationVariables,
        TContext
      > => {
      return useMutation(getSendPublicChatMessageMutationOptions(options), queryClient);
    }
    export const getListPublicChatMessagesUrl = (key: string,
    params?: ListPublicChatMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/public/chat/${key}/messages?${stringifiedParams}` : `/api/public/chat/${key}/messages`
}

export const listPublicChatMessages = async (key: string,
    params?: ListPublicChatMessagesParams, options?: Parameters<typeof http>[1]): Promise<ListPublicChatMessages200> => {

  return http<ListPublicChatMessages200>(getListPublicChatMessagesUrl(key,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPublicChatMessagesQueryKey = (key: string,
    params?: ListPublicChatMessagesParams,) => {
    return [
    `/api/public/chat/${key}/messages`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPublicChatMessagesQueryOptions = <TData = Awaited<ReturnType<typeof listPublicChatMessages>>, TError = ErrorType<unknown>>(key: string,
    params?: ListPublicChatMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicChatMessages>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPublicChatMessagesQueryKey(key,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPublicChatMessages>>> = ({ signal }) => listPublicChatMessages(key,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: key !== null && key !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPublicChatMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPublicChatMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof listPublicChatMessages>>>
export type ListPublicChatMessagesQueryError = ErrorType<unknown>


export function useListPublicChatMessages<TData = Awaited<ReturnType<typeof listPublicChatMessages>>, TError = ErrorType<unknown>>(
 key: string,
    params: undefined |  ListPublicChatMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicChatMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicChatMessages>>,
          TError,
          Awaited<ReturnType<typeof listPublicChatMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublicChatMessages<TData = Awaited<ReturnType<typeof listPublicChatMessages>>, TError = ErrorType<unknown>>(
 key: string,
    params?: ListPublicChatMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicChatMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPublicChatMessages>>,
          TError,
          Awaited<ReturnType<typeof listPublicChatMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPublicChatMessages<TData = Awaited<ReturnType<typeof listPublicChatMessages>>, TError = ErrorType<unknown>>(
 key: string,
    params?: ListPublicChatMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicChatMessages>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListPublicChatMessages<TData = Awaited<ReturnType<typeof listPublicChatMessages>>, TError = ErrorType<unknown>>(
 key: string,
    params?: ListPublicChatMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPublicChatMessages>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPublicChatMessagesQueryOptions(key,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






