// Local validation of the production stack (feature `staging`): each step proves one check of
// .specs/features/staging/checks.md against docker-compose.prod.yml running on this machine.
//   node scripts/staging-smoke.mjs up        build and start the stack (.env.staging-local)
//   node scripts/staging-smoke.mjs <step>    one check; exits 1 on the first failed assertion
//   node scripts/staging-smoke.mjs all       every step, in order
//   node scripts/staging-smoke.mjs down      stop the stack and remove its volumes
import { execFileSync, spawnSync } from 'node:child_process'
import { randomBytes, randomUUID } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const out = (line) => process.stdout.write(`${line}\n`)
const fail = (line) => process.stderr.write(`${line}\n`)

// Caddy's internal CA signs the local certificate.
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'

const ENV_FILE = '.env.staging-local'
const PROJECT = 'bens-staging-local'
const COMPOSE = [
  'compose',
  '-p',
  PROJECT,
  '-f',
  'docker-compose.prod.yml',
  '-f',
  'docker-compose.staging-local.yml',
  '--env-file',
  ENV_FILE,
]
const MAILPIT = process.env.E2E_MAILPIT_URL ?? 'http://localhost:8025'
const PASSWORD = 'senha-segura-123'

function localEnv() {
  if (!existsSync(ENV_FILE)) {
    const secret = () => randomBytes(24).toString('hex')
    writeFileSync(
      ENV_FILE,
      [
        '# Generated by scripts/staging-smoke.mjs: local validation only.',
        'SITE_ADDRESS=localhost',
        // 443 may be taken on a workstation; the ports are the stack's own choice.
        'HTTP_PORT=8080',
        'HTTPS_PORT=8443',
        'APP_URL=https://localhost:8443',
        'POSTGRES_USER=bens',
        `POSTGRES_PASSWORD=${secret()}`,
        'POSTGRES_DB=bens',
        `APP_DB_PASSWORD=${secret()}`,
        `BETTER_AUTH_SECRET=${secret()}`,
        'S3_ENDPOINT=http://localhost:9000',
        'S3_BUCKET=bens-staging-local',
        'S3_ACCESS_KEY_ID=bens',
        'S3_SECRET_ACCESS_KEY=bens-minio',
        'SMTP_URL=smtp://host.docker.internal:1025',
        'EMAIL_FROM="Bens Seguros <nao-responda@bensseguros.local>"',
        'LOG_LEVEL=warn',
        '',
      ].join('\n'),
    )
  }
  return Object.fromEntries(
    readFileSync(ENV_FILE, 'utf8')
      .split('\n')
      .filter((line) => /^[A-Z_]+=/.test(line))
      .map((line) => {
        const index = line.indexOf('=')
        return [line.slice(0, index), line.slice(index + 1).replace(/^"|"$/g, '')]
      }),
  )
}

const env = localEnv()
const BASE = env.APP_URL
const HTTP_BASE = `http://localhost:${env.HTTP_PORT}`

function docker(args, options = {}) {
  return execFileSync('docker', args, { encoding: 'utf8', ...options }).trim()
}

function compose(...args) {
  return docker([...COMPOSE, ...args])
}

function assert(condition, message) {
  if (!condition) throw new Error(message)
  out(`  ok - ${message}`)
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms))

async function waitFor(check, label, attempts = 60) {
  for (let i = 0; i < attempts; i++) {
    if (await check().catch(() => false)) return
    await sleep(1000)
  }
  throw new Error(`timed out waiting for ${label}`)
}

function post(path, body, headers = {}) {
  return fetch(`${BASE}${path}`, {
    method: 'POST',
    redirect: 'manual',
    headers: { 'content-type': 'application/json', origin: BASE, ...headers },
    body: JSON.stringify(body),
  })
}

// The auth rate limit is per client address, and every request from this machine shares one.
function clearRateLimits() {
  compose(
    'exec',
    '-T',
    'postgres',
    'psql',
    '-U',
    env.POSTGRES_USER,
    '-d',
    env.POSTGRES_DB,
    '-qc',
    'DELETE FROM "RateLimit"',
  )
}

async function emailLink(to) {
  let url
  await waitFor(
    async () => {
      const search = await (
        await fetch(`${MAILPIT}/api/v1/search?query=${encodeURIComponent(`to:"${to}"`)}`)
      ).json()
      const [message] = search.messages
      if (!message) return false
      const body = await (await fetch(`${MAILPIT}/api/v1/message/${message.ID}`)).json()
      url = body.Text.match(/https?:\/\/\S+\/api\/auth\/\S+/)?.[0]
      return url !== undefined
    },
    `the e-mail to ${to}`,
    30,
  )
  return url
}

// A verified user and the session cookie of a fresh sign-in.
async function signedIn() {
  clearRateLimits()
  const email = `staging-${randomUUID()}@example.com`
  const signUp = await post('/api/auth/sign-up/email', {
    name: 'Maria Souza',
    email,
    password: PASSWORD,
  })
  if (signUp.status !== 200) throw new Error(`sign-up: ${signUp.status}`)
  const verify = await fetch(await emailLink(email), { redirect: 'manual' })
  if (verify.status !== 302) throw new Error(`verify-email: ${verify.status}`)
  const signIn = await post('/api/auth/sign-in/email', { email, password: PASSWORD })
  if (signIn.status !== 200) throw new Error(`sign-in: ${signIn.status}`)
  return { email, setCookies: signIn.headers.getSetCookie() }
}

function containerTime(service, field) {
  const id = compose('ps', '-a', '-q', service)
  return new Date(docker(['inspect', '-f', `{{.State.${field}}}`, id]))
}

const steps = {
  async up() {
    compose('up', '-d', '--build', '--wait')
    out(`  stack up at ${BASE}`)
  },

  async down() {
    compose('down', '--volumes')
  },

  // C1
  async health() {
    // A fresh start of both, so the order below is this deploy's and not a leftover of earlier runs.
    compose('rm', '--stop', '--force', 'server', 'migrate')
    compose('up', '-d', '--wait', 'server')
    const migrateExit = docker([
      'inspect',
      '-f',
      '{{.State.ExitCode}}',
      compose('ps', '-a', '-q', 'migrate'),
    ])
    assert(migrateExit === '0', 'migrate exited with code 0')
    assert(
      containerTime('migrate', 'FinishedAt') < containerTime('server', 'StartedAt'),
      'migrate finished before the server started',
    )
    const health = await fetch(`${BASE}/api/health`)
    assert(health.status === 200, `GET /api/health -> ${health.status}`)
    assert(JSON.stringify(await health.json()) === '{"status":"ok"}', 'body is {"status":"ok"}')

    compose('stop', 'server')
    try {
      const down = await fetch(`${BASE}/api/health`)
      assert(down.status === 502, `with the server stopped, GET /api/health -> ${down.status}`)
    } finally {
      compose('start', 'server')
      await waitFor(async () => (await fetch(`${BASE}/api/health`)).status === 200, 'the server')
    }
  },

  // C2
  async spa() {
    const login = await fetch(`${BASE}/login`)
    const html = await login.text()
    assert(login.status === 200, `GET /login -> ${login.status}`)
    assert(html.includes('<div id="root">'), '/login is the SPA index.html')
    const asset = html.match(/\/assets\/[^"]+\.js/)?.[0]
    assert(asset !== undefined, `index.html references a hashed asset (${asset})`)
    const found = await fetch(`${BASE}${asset}`)
    assert(found.status === 200, `GET ${asset} -> ${found.status}`)
    assert(
      found.headers.get('cache-control') === 'public, max-age=31536000, immutable',
      `cache-control: ${found.headers.get('cache-control')}`,
    )
    const missing = await fetch(`${BASE}/assets/nao-existe-123.js`)
    assert(missing.status === 404, `GET /assets/nao-existe-123.js -> ${missing.status}`)
  },

  // C3
  async redirect() {
    const response = await fetch(`${HTTP_BASE}/`, { redirect: 'manual' })
    assert(response.status === 308, `GET ${HTTP_BASE}/ -> ${response.status}`)
    // Caddy redirects to the standard HTTPS port (443), as on the VPS; locally the stack listens on
    // another port, so the host and the scheme are what this proves.
    assert(
      response.headers.get('location') === 'https://localhost/',
      `location: ${response.headers.get('location')}`,
    )
  },

  // C4
  async ports() {
    const config = JSON.parse(
      docker([
        'compose',
        '-f',
        'docker-compose.prod.yml',
        '--env-file',
        ENV_FILE,
        'config',
        '--format',
        'json',
      ]),
    )
    assert(
      config.services.server.ports === undefined,
      'docker-compose.prod.yml publishes no server port',
    )
    assert(
      config.services.postgres.ports === undefined,
      'docker-compose.prod.yml publishes no postgres port',
    )
    const published = compose('port', 'postgres', '5432')
    assert(
      published.startsWith('127.0.0.1:'),
      `the local override publishes postgres on loopback only (${published})`,
    )
  },

  // C5
  async 'non-root'() {
    const uid = compose('exec', '-T', 'server', 'id', '-u')
    assert(uid !== '0', `server runs as uid ${uid}`)
  },

  // C6, C7
  async provision() {
    const name = `bens-provision-${randomUUID().slice(0, 8)}`
    docker([
      'run',
      '-d',
      '--rm',
      '--name',
      name,
      '-e',
      'POSTGRES_PASSWORD=owner',
      '-v',
      `${process.cwd()}/docker/postgres/init:/provision:ro`,
      'postgres:18-alpine',
    ])
    try {
      await waitFor(
        async () =>
          spawnSync('docker', ['exec', name, 'pg_isready', '-h', '127.0.0.1', '-U', 'postgres'])
            .status === 0,
        'the throwaway postgres',
      )
      await sleep(1000)
      const run = (password) =>
        spawnSync(
          'docker',
          [
            'exec',
            '-e',
            `APP_DB_PASSWORD=${password}`,
            '-e',
            'POSTGRES_USER=postgres',
            '-e',
            'POSTGRES_DB=postgres',
            name,
            '/provision/01-app-role.sh',
          ],
          { encoding: 'utf8' },
        )
      const roles = () =>
        docker([
          'exec',
          name,
          'psql',
          '-U',
          'postgres',
          '-tAc',
          "SELECT rolsuper || '|' || rolbypassrls FROM pg_roles WHERE rolname = 'bens_app'",
        ])
      // Over the container address: pg_hba trusts 127.0.0.1, which would accept any password.
      const ip = docker([
        'inspect',
        '-f',
        '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}',
        name,
      ])
      const login = (password) =>
        spawnSync('docker', [
          'exec',
          name,
          'psql',
          `postgresql://bens_app:${password}@${ip}/postgres`,
          '-tAc',
          'SELECT 1',
        ]).status === 0

      const empty = run('')
      assert(empty.status !== 0, `empty APP_DB_PASSWORD exits ${empty.status}`)
      assert(roles() === '', 'and creates no role')

      assert(run('senha-x').status === 0, 'APP_DB_PASSWORD=senha-x exits 0')
      assert(roles() === 'false|false', 'bens_app is NOSUPERUSER NOBYPASSRLS')
      assert(login('senha-x'), 'bens_app logs in with senha-x')

      assert(run('senha-y').status === 0, 'a second run with senha-y exits 0')
      assert(login('senha-y'), 'bens_app logs in with senha-y')
      assert(!login('senha-x'), 'senha-x is refused')
    } finally {
      docker(['stop', name])
    }
  },

  // C8
  async cookie() {
    const { setCookies } = await signedIn()
    const cookie = setCookies.find((item) => item.startsWith('__Secure-better-auth.session_token='))
    assert(
      cookie !== undefined,
      `session cookie has the __Secure- prefix (${setCookies.map((c) => c.split('=')[0]).join(', ')})`,
    )
    for (const attribute of [
      /;\s*Secure/i,
      /;\s*HttpOnly/i,
      /;\s*SameSite=Lax/i,
      /;\s*Path=\/(;|$)/i,
    ]) {
      assert(attribute.test(cookie), `cookie has ${attribute.source.replace(/\\s\*|;|\(.*$/g, '')}`)
    }
    assert(!/;\s*Domain=/i.test(cookie), 'cookie has no Domain (host-only)')
  },

  // C9
  async origin() {
    const response = await post(
      '/api/auth/sign-in/email',
      { email: 'x@example.com', password: PASSWORD },
      { origin: 'https://evil.example' },
    )
    assert(response.status === 403, `POST from https://evil.example -> ${response.status}`)
  },

  // C10
  async 'forwarded-for'() {
    clearRateLimits()
    const statuses = []
    for (let i = 0; i < 11; i++) {
      const response = await post(
        '/api/auth/sign-in/email',
        { email: 'ninguem@example.com', password: 'senha-errada-000' },
        { 'x-forwarded-for': `203.0.113.${i + 1}` },
      )
      statuses.push(response.status)
    }
    assert(
      !statuses.slice(0, 10).includes(429),
      `first 10 sign-ins are not 429 (${statuses.slice(0, 10).join(' ')})`,
    )
    assert(statuses[10] === 429, `the 11th is 429 despite a new X-Forwarded-For (${statuses[10]})`)
    clearRateLimits()
  },

  // C11
  async docs() {
    const response = await fetch(`${BASE}/api/docs`)
    assert(response.status === 404, `GET /api/docs -> ${response.status}`)
  },

  // C12
  async headers() {
    const response = await fetch(`${BASE}/login`)
    const expected = {
      'strict-transport-security': 'max-age=31536000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'referrer-policy': 'strict-origin-when-cross-origin',
      'x-frame-options': 'DENY',
      'content-security-policy':
        "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
    }
    for (const [name, value] of Object.entries(expected)) {
      assert(response.headers.get(name) === value, `${name}: ${response.headers.get(name)}`)
    }
  },

  // C13
  async e2e() {
    const result = spawnSync('pnpm', ['e2e'], {
      stdio: 'inherit',
      env: {
        ...process.env,
        E2E_BASE_URL: BASE,
        E2E_DATABASE_URL: `postgresql://bens_app:${env.APP_DB_PASSWORD}@localhost:${process.env.STAGING_LOCAL_DB_PORT ?? '55432'}/${env.POSTGRES_DB}`,
      },
    })
    assert(result.status === 0, `pnpm e2e against ${BASE} exits ${result.status}`)
  },

  // C14
  async socket() {
    const { setCookies } = await signedIn()
    const cookie = setCookies.map((item) => item.split(';')[0]).join('; ')
    const { io } = createRequire(new URL('../apps/server/package.json', import.meta.url))(
      'socket.io-client',
    )
    const socket = io(BASE, {
      path: '/socket.io',
      transports: ['websocket'],
      extraHeaders: { cookie, origin: BASE },
      rejectUnauthorized: false,
      reconnection: false,
    })
    const outcome = await new Promise((resolve) => {
      socket.once('connect', () => resolve('connected'))
      socket.once('connect_error', (error) => resolve(error.message))
      setTimeout(() => resolve('timeout'), 10_000)
    })
    socket.disconnect()
    assert(
      outcome === 'connected',
      `wss://localhost:${env.HTTPS_PORT}/socket.io with the session cookie: ${outcome}`,
    )
  },

  // C15
  async runbook() {
    const text = readFileSync('docs/runbooks/staging.md', 'utf8')
    const headings = [...text.matchAll(/^## (.+)$/gm)].map((match) => match[1])
    const order = ['DNS', '.env', 'Subir', 'Verificar', 'Rollback']
    const found = order.map((prefix) => headings.findIndex((heading) => heading.startsWith(prefix)))
    assert(
      found.every((index) => index >= 0),
      `sections present: ${order.join(', ')}`,
    )
    assert(
      found.every((index, i) => i === 0 || index > found[i - 1]),
      'in that order',
    )
    for (const file of [
      'docker-compose.prod.yml',
      '.env.prod.example',
      'docker/postgres/init/01-app-role.sh',
      'Caddyfile',
    ]) {
      assert(text.includes(file) && existsSync(file), `cites ${file}, which exists`)
    }
  },
}

const ORDER = [
  'health',
  'spa',
  'redirect',
  'ports',
  'non-root',
  'provision',
  'cookie',
  'origin',
  'forwarded-for',
  'docs',
  'headers',
  'socket',
  'runbook',
  'e2e',
]

const name = process.argv[2]
const selected = name === 'all' ? ORDER : [name]
if (!name || selected.some((step) => !(step in steps))) {
  fail(`usage: node scripts/staging-smoke.mjs <up|down|all|${ORDER.join('|')}>`)
  process.exit(2)
}
for (const step of selected) {
  out(`# ${step}`)
  try {
    await steps[step]()
  } catch (error) {
    fail(`  not ok - ${error instanceof Error ? error.message : error}`)
    process.exit(1)
  }
}
