/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PreviewExampleCommission200,
  PreviewExampleCommissionParams
} from '../../model';

import { http } from '../../../lib/http';
import type { ErrorType } from '../../../lib/http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPreviewExampleCommissionUrl = (params: PreviewExampleCommissionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/examples/commission-preview?${stringifiedParams}` : `/api/v1/examples/commission-preview`
}

export const previewExampleCommission = async (params: PreviewExampleCommissionParams, options?: Parameters<typeof http>[1]): Promise<PreviewExampleCommission200> => {

  return http<PreviewExampleCommission200>(getPreviewExampleCommissionUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPreviewExampleCommissionQueryKey = (params?: PreviewExampleCommissionParams,) => {
    return [
    `/api/v1/examples/commission-preview`, ...(params ? [params] : [])
    ] as const;
    }


export const getPreviewExampleCommissionQueryOptions = <TData = Awaited<ReturnType<typeof previewExampleCommission>>, TError = ErrorType<unknown>>(params: PreviewExampleCommissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewExampleCommission>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewExampleCommissionQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewExampleCommission>>> = ({ signal }) => previewExampleCommission(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewExampleCommission>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PreviewExampleCommissionQueryResult = NonNullable<Awaited<ReturnType<typeof previewExampleCommission>>>
export type PreviewExampleCommissionQueryError = ErrorType<unknown>


export function usePreviewExampleCommission<TData = Awaited<ReturnType<typeof previewExampleCommission>>, TError = ErrorType<unknown>>(
 params: PreviewExampleCommissionParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewExampleCommission>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewExampleCommission>>,
          TError,
          Awaited<ReturnType<typeof previewExampleCommission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewExampleCommission<TData = Awaited<ReturnType<typeof previewExampleCommission>>, TError = ErrorType<unknown>>(
 params: PreviewExampleCommissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewExampleCommission>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewExampleCommission>>,
          TError,
          Awaited<ReturnType<typeof previewExampleCommission>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewExampleCommission<TData = Awaited<ReturnType<typeof previewExampleCommission>>, TError = ErrorType<unknown>>(
 params: PreviewExampleCommissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewExampleCommission>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePreviewExampleCommission<TData = Awaited<ReturnType<typeof previewExampleCommission>>, TError = ErrorType<unknown>>(
 params: PreviewExampleCommissionParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewExampleCommission>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPreviewExampleCommissionQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






