/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOrganization200,
  OnboardOrganization200,
  OnboardOrganizationBody,
  RenameOrganization200,
  RenameOrganizationBody,
  SetActiveOrganization200,
  SetActiveOrganizationBody,
  UpdateOrganizationBranding200,
  UpdateOrganizationBrandingBody,
  UploadOrganizationLogo200,
  UploadOrganizationLogoBody
} from '../../model';

import { http } from '../../../lib/http';
import type { ErrorType } from '../../../lib/http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getOnboardOrganizationUrl = () => {




  return `/api/v1/onboarding`
}

export const onboardOrganization = async (onboardOrganizationBody: OnboardOrganizationBody, options?: Parameters<typeof http>[1]): Promise<OnboardOrganization200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<OnboardOrganization200>(getOnboardOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(onboardOrganizationBody)
  }
);}





export const getOnboardOrganizationMutationKey = () => ['onboardOrganization'] as const;

export const getOnboardOrganizationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardOrganization>>, TError,OnboardOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof onboardOrganization>>, TError,OnboardOrganizationMutationVariables, TContext> => {

const mutationKey = getOnboardOrganizationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof onboardOrganization>>, OnboardOrganizationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  onboardOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OnboardOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof onboardOrganization>>>
    export type OnboardOrganizationMutationBody = OnboardOrganizationBody
    export type OnboardOrganizationMutationError = ErrorType<unknown>
    export type OnboardOrganizationMutationVariables = {data: OnboardOrganizationBody}

    export const useOnboardOrganization = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardOrganization>>, TError,OnboardOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof onboardOrganization>>,
        TError,
        OnboardOrganizationMutationVariables,
        TContext
      > => {
      return useMutation(getOnboardOrganizationMutationOptions(options), queryClient);
    }
    export const getSetActiveOrganizationUrl = () => {




  return `/api/v1/me/active-organization`
}

export const setActiveOrganization = async (setActiveOrganizationBody: SetActiveOrganizationBody, options?: Parameters<typeof http>[1]): Promise<SetActiveOrganization200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<SetActiveOrganization200>(getSetActiveOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setActiveOrganizationBody)
  }
);}





export const getSetActiveOrganizationMutationKey = () => ['setActiveOrganization'] as const;

export const getSetActiveOrganizationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,SetActiveOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,SetActiveOrganizationMutationVariables, TContext> => {

const mutationKey = getSetActiveOrganizationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setActiveOrganization>>, SetActiveOrganizationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  setActiveOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetActiveOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof setActiveOrganization>>>
    export type SetActiveOrganizationMutationBody = SetActiveOrganizationBody
    export type SetActiveOrganizationMutationError = ErrorType<unknown>
    export type SetActiveOrganizationMutationVariables = {data: SetActiveOrganizationBody}

    export const useSetActiveOrganization = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,SetActiveOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setActiveOrganization>>,
        TError,
        SetActiveOrganizationMutationVariables,
        TContext
      > => {
      return useMutation(getSetActiveOrganizationMutationOptions(options), queryClient);
    }
    export const getGetOrganizationUrl = () => {




  return `/api/v1/organization`
}

export const getOrganization = async ( options?: Parameters<typeof http>[1]): Promise<GetOrganization200> => {

  return http<GetOrganization200>(getGetOrganizationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationQueryKey = () => {
    return [
    `/api/v1/organization`
    ] as const;
    }


export const getGetOrganizationQueryOptions = <TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganization>>> = ({ signal }) => getOrganization({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganizationQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganization>>>
export type GetOrganizationQueryError = ErrorType<unknown>


export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganization>>,
          TError,
          Awaited<ReturnType<typeof getOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganization>>,
          TError,
          Awaited<ReturnType<typeof getOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganizationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getRenameOrganizationUrl = () => {




  return `/api/v1/organization`
}

export const renameOrganization = async (renameOrganizationBody: RenameOrganizationBody, options?: Parameters<typeof http>[1]): Promise<RenameOrganization200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<RenameOrganization200>(getRenameOrganizationUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renameOrganizationBody)
  }
);}





export const getRenameOrganizationMutationKey = () => ['renameOrganization'] as const;

export const getRenameOrganizationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameOrganization>>, TError,RenameOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof renameOrganization>>, TError,RenameOrganizationMutationVariables, TContext> => {

const mutationKey = getRenameOrganizationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameOrganization>>, RenameOrganizationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  renameOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenameOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof renameOrganization>>>
    export type RenameOrganizationMutationBody = RenameOrganizationBody
    export type RenameOrganizationMutationError = ErrorType<unknown>
    export type RenameOrganizationMutationVariables = {data: RenameOrganizationBody}

    export const useRenameOrganization = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameOrganization>>, TError,RenameOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameOrganization>>,
        TError,
        RenameOrganizationMutationVariables,
        TContext
      > => {
      return useMutation(getRenameOrganizationMutationOptions(options), queryClient);
    }
    export const getUpdateOrganizationBrandingUrl = () => {




  return `/api/v1/organization/branding`
}

export const updateOrganizationBranding = async (updateOrganizationBrandingBody: UpdateOrganizationBrandingBody, options?: Parameters<typeof http>[1]): Promise<UpdateOrganizationBranding200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<UpdateOrganizationBranding200>(getUpdateOrganizationBrandingUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateOrganizationBrandingBody)
  }
);}





export const getUpdateOrganizationBrandingMutationKey = () => ['updateOrganizationBranding'] as const;

export const getUpdateOrganizationBrandingMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationBranding>>, TError,UpdateOrganizationBrandingMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationBranding>>, TError,UpdateOrganizationBrandingMutationVariables, TContext> => {

const mutationKey = getUpdateOrganizationBrandingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganizationBranding>>, UpdateOrganizationBrandingMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  updateOrganizationBranding(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganizationBrandingMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganizationBranding>>>
    export type UpdateOrganizationBrandingMutationBody = UpdateOrganizationBrandingBody
    export type UpdateOrganizationBrandingMutationError = ErrorType<unknown>
    export type UpdateOrganizationBrandingMutationVariables = {data: UpdateOrganizationBrandingBody}

    export const useUpdateOrganizationBranding = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationBranding>>, TError,UpdateOrganizationBrandingMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganizationBranding>>,
        TError,
        UpdateOrganizationBrandingMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateOrganizationBrandingMutationOptions(options), queryClient);
    }
    export const getUploadOrganizationLogoUrl = () => {




  return `/api/v1/organization/logo`
}

export const uploadOrganizationLogo = async (uploadOrganizationLogoBody: UploadOrganizationLogoBody, options?: Parameters<typeof http>[1]): Promise<UploadOrganizationLogo200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<UploadOrganizationLogo200>(getUploadOrganizationLogoUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(uploadOrganizationLogoBody)
  }
);}





export const getUploadOrganizationLogoMutationKey = () => ['uploadOrganizationLogo'] as const;

export const getUploadOrganizationLogoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadOrganizationLogo>>, TError,UploadOrganizationLogoMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadOrganizationLogo>>, TError,UploadOrganizationLogoMutationVariables, TContext> => {

const mutationKey = getUploadOrganizationLogoMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadOrganizationLogo>>, UploadOrganizationLogoMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  uploadOrganizationLogo(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadOrganizationLogoMutationResult = NonNullable<Awaited<ReturnType<typeof uploadOrganizationLogo>>>
    export type UploadOrganizationLogoMutationBody = UploadOrganizationLogoBody
    export type UploadOrganizationLogoMutationError = ErrorType<unknown>
    export type UploadOrganizationLogoMutationVariables = {data: UploadOrganizationLogoBody}

    export const useUploadOrganizationLogo = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadOrganizationLogo>>, TError,UploadOrganizationLogoMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadOrganizationLogo>>,
        TError,
        UploadOrganizationLogoMutationVariables,
        TContext
      > => {
      return useMutation(getUploadOrganizationLogoMutationOptions(options), queryClient);
    }
    export const getRemoveOrganizationLogoUrl = () => {




  return `/api/v1/organization/logo`
}

export const removeOrganizationLogo = async ( options?: Parameters<typeof http>[1]): Promise<void> => {

  return http<void>(getRemoveOrganizationLogoUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRemoveOrganizationLogoMutationKey = () => ['removeOrganizationLogo'] as const;

export const getRemoveOrganizationLogoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeOrganizationLogo>>, TError,void, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof removeOrganizationLogo>>, TError,void, TContext> => {

const mutationKey = getRemoveOrganizationLogoMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeOrganizationLogo>>, void> = () => {


          return  removeOrganizationLogo(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveOrganizationLogoMutationResult = NonNullable<Awaited<ReturnType<typeof removeOrganizationLogo>>>

    export type RemoveOrganizationLogoMutationError = ErrorType<unknown>


    export const useRemoveOrganizationLogo = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeOrganizationLogo>>, TError,void, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeOrganizationLogo>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRemoveOrganizationLogoMutationOptions(options), queryClient);
    }
    export const getGetOrganizationLogoUrl = () => {




  return `/api/v1/organization/logo`
}

export const getOrganizationLogo = async ( options?: Parameters<typeof http>[1]): Promise<void> => {

  return http<void>(getGetOrganizationLogoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationLogoQueryKey = () => {
    return [
    `/api/v1/organization/logo`
    ] as const;
    }


export const getGetOrganizationLogoQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationLogo>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLogo>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationLogoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationLogo>>> = ({ signal }) => getOrganizationLogo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLogo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganizationLogoQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationLogo>>>
export type GetOrganizationLogoQueryError = ErrorType<unknown>


export function useGetOrganizationLogo<TData = Awaited<ReturnType<typeof getOrganizationLogo>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLogo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationLogo>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationLogo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizationLogo<TData = Awaited<ReturnType<typeof getOrganizationLogo>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLogo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationLogo>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationLogo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganizationLogo<TData = Awaited<ReturnType<typeof getOrganizationLogo>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLogo>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOrganizationLogo<TData = Awaited<ReturnType<typeof getOrganizationLogo>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLogo>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganizationLogoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






