/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bens Seguros API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetOrganization200,
  OnboardOrganization200,
  OnboardOrganizationBody,
  RenameOrganization200,
  RenameOrganizationBody,
  SetActiveOrganization200,
  SetActiveOrganizationBody
} from '../../model';

import { http } from '../../../lib/http';
import type { ErrorType } from '../../../lib/http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getOnboardOrganizationUrl = () => {




  return `/api/v1/onboarding`
}

export const onboardOrganization = async (onboardOrganizationBody: OnboardOrganizationBody, options?: Parameters<typeof http>[1]): Promise<OnboardOrganization200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<OnboardOrganization200>(getOnboardOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(onboardOrganizationBody)
  }
);}





export const getOnboardOrganizationMutationKey = () => ['onboardOrganization'] as const;

export const getOnboardOrganizationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardOrganization>>, TError,OnboardOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof onboardOrganization>>, TError,OnboardOrganizationMutationVariables, TContext> => {

const mutationKey = getOnboardOrganizationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof onboardOrganization>>, OnboardOrganizationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  onboardOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OnboardOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof onboardOrganization>>>
    export type OnboardOrganizationMutationBody = OnboardOrganizationBody
    export type OnboardOrganizationMutationError = ErrorType<unknown>
    export type OnboardOrganizationMutationVariables = {data: OnboardOrganizationBody}

    export const useOnboardOrganization = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardOrganization>>, TError,OnboardOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof onboardOrganization>>,
        TError,
        OnboardOrganizationMutationVariables,
        TContext
      > => {
      return useMutation(getOnboardOrganizationMutationOptions(options), queryClient);
    }
    export const getSetActiveOrganizationUrl = () => {




  return `/api/v1/me/active-organization`
}

export const setActiveOrganization = async (setActiveOrganizationBody: SetActiveOrganizationBody, options?: Parameters<typeof http>[1]): Promise<SetActiveOrganization200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<SetActiveOrganization200>(getSetActiveOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(setActiveOrganizationBody)
  }
);}





export const getSetActiveOrganizationMutationKey = () => ['setActiveOrganization'] as const;

export const getSetActiveOrganizationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,SetActiveOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,SetActiveOrganizationMutationVariables, TContext> => {

const mutationKey = getSetActiveOrganizationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setActiveOrganization>>, SetActiveOrganizationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  setActiveOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetActiveOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof setActiveOrganization>>>
    export type SetActiveOrganizationMutationBody = SetActiveOrganizationBody
    export type SetActiveOrganizationMutationError = ErrorType<unknown>
    export type SetActiveOrganizationMutationVariables = {data: SetActiveOrganizationBody}

    export const useSetActiveOrganization = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setActiveOrganization>>, TError,SetActiveOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setActiveOrganization>>,
        TError,
        SetActiveOrganizationMutationVariables,
        TContext
      > => {
      return useMutation(getSetActiveOrganizationMutationOptions(options), queryClient);
    }
    export const getGetOrganizationUrl = () => {




  return `/api/v1/organization`
}

export const getOrganization = async ( options?: Parameters<typeof http>[1]): Promise<GetOrganization200> => {

  return http<GetOrganization200>(getGetOrganizationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationQueryKey = () => {
    return [
    `/api/v1/organization`
    ] as const;
    }


export const getGetOrganizationQueryOptions = <TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganization>>> = ({ signal }) => getOrganization({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrganizationQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganization>>>
export type GetOrganizationQueryError = ErrorType<unknown>


export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganization>>,
          TError,
          Awaited<ReturnType<typeof getOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganization>>,
          TError,
          Awaited<ReturnType<typeof getOrganization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOrganization<TData = Awaited<ReturnType<typeof getOrganization>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganization>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrganizationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getRenameOrganizationUrl = () => {




  return `/api/v1/organization`
}

export const renameOrganization = async (renameOrganizationBody: RenameOrganizationBody, options?: Parameters<typeof http>[1]): Promise<RenameOrganization200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return http<RenameOrganization200>(getRenameOrganizationUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renameOrganizationBody)
  }
);}





export const getRenameOrganizationMutationKey = () => ['renameOrganization'] as const;

export const getRenameOrganizationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameOrganization>>, TError,RenameOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof renameOrganization>>, TError,RenameOrganizationMutationVariables, TContext> => {

const mutationKey = getRenameOrganizationMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameOrganization>>, RenameOrganizationMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  renameOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenameOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof renameOrganization>>>
    export type RenameOrganizationMutationBody = RenameOrganizationBody
    export type RenameOrganizationMutationError = ErrorType<unknown>
    export type RenameOrganizationMutationVariables = {data: RenameOrganizationBody}

    export const useRenameOrganization = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameOrganization>>, TError,RenameOrganizationMutationVariables, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameOrganization>>,
        TError,
        RenameOrganizationMutationVariables,
        TContext
      > => {
      return useMutation(getRenameOrganizationMutationOptions(options), queryClient);
    }
